INSERT INTO tuning_guides (
  class_id,
  title,
  source,
  source_url,
  file_url,
  file_type,
  description,
  year,
  tags,
  auto_scraped,
  scrape_successful,
  is_public,
  downloads,
  rating
)
SELECT
  bc.id,
  g.title,
  g.source,
  g.source_url,
  g.file_url,
  g.file_type,
  g.description,
  g.year,
  g.tags,
  g.auto_scraped,
  g.scrape_successful,
  g.is_public,
  g.downloads,
  g.rating
FROM (
  VALUES
    (
      'international dragon',
      'North Sails Dragon Tuning Guide 2025',
      'North Sails',
      'https://www.northsails.com/sailing/en/ondesign/resources/dragon',
      'https://www.northsails.com/sailing/en/ondesign/resources/dragon',
      'link',
      'Official North Sails tuning guide for International Dragon fleets, including rig tune numbers and sail shapes.',
      2025,
      ARRAY['rigging','light-air','sail-trim'],
      false,
      true,
      true,
      128,
      4.8
    ),
    (
      'international dragon',
      'Quantum Dragon Tuning Matrix',
      'Quantum Sails',
      'https://www.quantumsails.com/en/resources/tuning-guides',
      'https://www.quantumsails.com/en/resources/tuning-guides',
      'link',
      'Matrix of Dragon tuning settings for light, medium, and heavy conditions with mast step and rig tension notes.',
      2024,
      ARRAY['heavy-air','setup','quantum'],
      false,
      true,
      true,
      74,
      4.6
    ),
    (
      'international dragon',
      'Dragon Class Tuning Workshop Notes',
      'International Dragon Association',
      'https://www.intdragon.net/',
      'https://www.intdragon.net/',
      'link',
      'Community-contributed tuning notes from Dragon World Championship workshops covering various wind ranges.',
      2024,
      ARRAY['rigging','workshop','community'],
      false,
      true,
      true,
      45,
      4.3
    ),
    (
      'swan 47',
      'Swan 47 Offshore Trim Reference',
      'North Sails',
      'https://northsails.com/swan/tuning-guide',
      NULL,
      'link',
      'Trim reference for Swan 47 offshore campaigns covering headsail leads, reefing plans, and backstay targets.',
      2023,
      ARRAY['offshore','trim','backstay'],
      false,
      true,
      true,
      63,
      4.4
    ),
    (
      'swan 47',
      'Hall Spars Rig Tune Checklist',
      'Hall Spars',
      'https://hallspars.com/resources/swan-47-rig-tune',
      NULL,
      'link',
      'Rig tune checklist for Hall Spars Swan 47 masts including dock tune numbers and underway adjustments.',
      2022,
      ARRAY['rigging','checklist'],
      false,
      true,
      true,
      41,
      4.2
    )
) AS g(
  class_key,
  title,
  source,
  source_url,
  file_url,
  file_type,
  description,
  year,
  tags,
  auto_scraped,
  scrape_successful,
  is_public,
  downloads,
  rating
)
JOIN boat_classes bc ON lower(bc.name) = g.class_key
ON CONFLICT DO NOTHING;
