/**
 * Excellence Framework Types
 *
 * Core type definitions for the Sailing Excellence Framework:
 * - Per-race timeline with 4 phases (Prep → Launch → Race → Review)
 * - Unified checklist model
 * - Excellence metrics tracking
 */

// ============================================
// Race Phases (The 4 Modes)
// ============================================

/**
 * The four phases of a race that a sailor progresses through
 */
export type RacePhase = 'prep' | 'launch' | 'race' | 'review';

/**
 * Categories for checklist items - aligned with race phases and activities
 */
export type ChecklistCategory =
  | 'forecast' // Weather, tide, conditions research
  | 'equipment' // Gear, boat setup
  | 'tactics' // Strategy planning
  | 'safety' // Safety checks, briefings
  | 'rigging' // Rig setup, tuning
  | 'start' // Starting sequence, approach
  | 'upwind' // Upwind leg execution
  | 'downwind' // Downwind leg execution
  | 'marks' // Mark roundings
  | 'finish' // Finish strategy
  | 'reflection' // Post-race review
  | 'learning' // Key learnings capture
  | 'logistics' // Travel, timing, logistics
  | 'crew'; // Crew coordination, communication

/**
 * Source of how a checklist item was created
 */
export type ChecklistItemSource =
  | 'template' // From a checklist template
  | 'ai_generated' // Generated by AI analysis
  | 'manual' // Manually added by user
  | 'learning_nudge'; // From adaptive learning system

/**
 * Status of a checklist item
 */
export type ChecklistItemStatus = 'pending' | 'in_progress' | 'completed' | 'skipped';

// ============================================
// Unified Checklist Item (Core data model)
// ============================================

/**
 * A single checklist item that can belong to any phase
 * This is the atomic unit of the excellence tracking system
 */
export interface RaceChecklistItem {
  id: string;
  sailorId: string;
  raceEventId: string;

  // Phase and category
  phase: RacePhase;
  category: ChecklistCategory;
  title: string;
  description?: string;

  // Status tracking
  status: ChecklistItemStatus;
  completedAt?: string;

  // Outcome rating (filled during Review phase)
  outcomeRating?: number; // 1-5
  outcomeNotes?: string;

  // Source tracking
  source: ChecklistItemSource;
  sourceLearningEventId?: string;

  // Personalization metadata
  isPersonalized: boolean;
  personalizationReason?: string;
  confidenceScore?: number; // 0-1

  // Template reference
  templateItemId?: string;

  // Ordering
  sortOrder: number;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Input for creating a new checklist item
 */
export interface CreateChecklistItemInput {
  raceEventId: string;
  phase: RacePhase;
  category: ChecklistCategory;
  title: string;
  description?: string;
  source: ChecklistItemSource;
  sourceLearningEventId?: string;
  isPersonalized?: boolean;
  personalizationReason?: string;
  confidenceScore?: number;
  templateItemId?: string;
  sortOrder?: number;
}

/**
 * Input for updating a checklist item status
 */
export interface UpdateChecklistStatusInput {
  itemId: string;
  status: ChecklistItemStatus;
}

/**
 * Input for rating a checklist item outcome
 */
export interface RateChecklistOutcomeInput {
  itemId: string;
  rating: number; // 1-5
  notes?: string;
}

// ============================================
// Checklist Templates
// ============================================

/**
 * A reusable checklist template
 */
export interface ChecklistTemplate {
  id: string;
  name: string;
  description?: string;
  phase: RacePhase;
  category: ChecklistCategory;
  title: string;
  defaultDescription?: string;
  createdBy?: string;
  isSystemTemplate: boolean;
  boatClassId?: string;
  raceType?: 'fleet' | 'team' | 'match' | 'distance';
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

// ============================================
// Excellence Metrics
// ============================================

/**
 * Phase mastery scores (0-100 per phase)
 */
export interface PhaseMasteryScores {
  prep: number;
  launch: number;
  start: number;
  upwind: number;
  downwind: number;
  markRounding: number;
  finish: number;
  review: number;
}

/**
 * Framework adoption scores for RegattaFlow Playbook techniques
 */
export interface FrameworkScores {
  puffResponse: number;
  delayedTack: number;
  windShiftAwareness: number;
  gettingInPhase: number;
  tacticalPositioning: number;
  boatHandling: number;
  [key: string]: number; // Allow additional frameworks
}

/**
 * Race result for outcome tracking
 */
export interface RaceResult {
  raceId: string;
  position: number;
  fleetSize?: number;
  date: string;
  venueName?: string;
}

/**
 * Outcome metrics tracking race results and trends
 */
export interface OutcomeMetrics {
  racesCompleted: number;
  averagePosition: number;
  positionTrend: 'improving' | 'stable' | 'declining';
  bestFinish: number;
  bestFinishRaceId?: string;
  recentResults: RaceResult[];
}

/**
 * AI-generated focus recommendation
 */
export interface FocusRecommendation {
  phase: RacePhase | string;
  title: string;
  reason: string;
  suggestedDrills?: string[];
  linkedLearningModuleId?: string;
  priority: 'high' | 'medium' | 'low';
}

/**
 * Complete excellence metrics for a sailor
 */
export interface ExcellenceMetrics {
  id: string;
  sailorId: string;
  seasonId?: string;

  // Mastery and framework scores
  phaseMastery: PhaseMasteryScores;
  frameworkScores: FrameworkScores;

  // Outcome metrics
  outcomes: OutcomeMetrics;

  // AI recommendations
  focusRecommendations: FocusRecommendation[];

  // Learning velocity
  eventsLast30Days: number;
  improvementTrend: 'improving' | 'stable' | 'declining';

  // Timestamps
  calculatedAt: string;
  createdAt: string;
  updatedAt: string;
}

// ============================================
// Race Timeline (Per-race progression)
// ============================================

/**
 * Status of a single phase in the race timeline
 */
export interface PhaseStatus {
  itemsTotal: number;
  itemsCompleted: number;
  itemsSkipped: number;
  completionRate: number; // 0-1
  averageRating?: number; // For review phase items
  startedAt?: string;
  completedAt?: string;
}

/**
 * Complete race timeline showing progression through all phases
 */
export interface RaceTimeline {
  raceEventId: string;
  currentPhase: RacePhase;
  phases: {
    prep: PhaseStatus;
    launch: PhaseStatus;
    race: PhaseStatus;
    review: PhaseStatus;
  };
  overallProgress: number; // 0-1
}

// ============================================
// Phase Configuration
// ============================================

/**
 * Display configuration for a phase
 */
export interface PhaseConfig {
  phase: RacePhase;
  label: string;
  shortLabel: string;
  icon: string;
  description: string;
  defaultCategories: ChecklistCategory[];
}

/**
 * Default phase configurations
 */
export const PHASE_CONFIGS: PhaseConfig[] = [
  {
    phase: 'prep',
    label: 'Preparation',
    shortLabel: 'Prep',
    icon: 'clipboard-check',
    description: 'Research conditions, plan strategy, prepare equipment',
    defaultCategories: ['forecast', 'equipment', 'tactics', 'logistics'],
  },
  {
    phase: 'launch',
    label: 'Launch',
    shortLabel: 'Launch',
    icon: 'anchor',
    description: 'Rig boat, safety checks, get on the water',
    defaultCategories: ['rigging', 'safety', 'crew'],
  },
  {
    phase: 'race',
    label: 'Race',
    shortLabel: 'Race',
    icon: 'flag-checkered',
    description: 'Execute race strategy through all legs',
    defaultCategories: ['start', 'upwind', 'marks', 'downwind', 'finish'],
  },
  {
    phase: 'review',
    label: 'Review',
    shortLabel: 'Review',
    icon: 'lightbulb',
    description: 'Capture learnings, rate outcomes, extract insights',
    defaultCategories: ['reflection', 'learning'],
  },
];

/**
 * Get phase config by phase
 */
export function getPhaseConfig(phase: RacePhase): PhaseConfig | undefined {
  return PHASE_CONFIGS.find((c) => c.phase === phase);
}

/**
 * Get the next phase in the timeline
 */
export function getNextPhase(currentPhase: RacePhase): RacePhase | null {
  const order: RacePhase[] = ['prep', 'launch', 'race', 'review'];
  const currentIndex = order.indexOf(currentPhase);
  if (currentIndex < order.length - 1) {
    return order[currentIndex + 1];
  }
  return null;
}

/**
 * Get the previous phase in the timeline
 */
export function getPreviousPhase(currentPhase: RacePhase): RacePhase | null {
  const order: RacePhase[] = ['prep', 'launch', 'race', 'review'];
  const currentIndex = order.indexOf(currentPhase);
  if (currentIndex > 0) {
    return order[currentIndex - 1];
  }
  return null;
}

// ============================================
// Database Row Types (for Supabase)
// ============================================

/**
 * Database row type for race_checklist_items table
 */
export interface RaceChecklistItemRow {
  id: string;
  sailor_id: string;
  race_event_id: string;
  phase: RacePhase;
  title: string;
  description: string | null;
  category: string | null;
  status: ChecklistItemStatus;
  completed_at: string | null;
  outcome_rating: number | null;
  outcome_notes: string | null;
  source: ChecklistItemSource;
  source_learning_event_id: string | null;
  is_personalized: boolean;
  personalization_reason: string | null;
  confidence_score: number | null;
  template_item_id: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

/**
 * Database row type for excellence_metrics table
 */
export interface ExcellenceMetricsRow {
  id: string;
  sailor_id: string;
  season_id: string | null;
  prep_mastery: number;
  launch_mastery: number;
  start_mastery: number;
  upwind_mastery: number;
  downwind_mastery: number;
  mark_rounding_mastery: number;
  finish_mastery: number;
  review_mastery: number;
  framework_scores: FrameworkScores;
  races_completed: number;
  average_position: number | null;
  position_trend: 'improving' | 'stable' | 'declining' | null;
  best_finish: number | null;
  best_finish_race_id: string | null;
  recent_results: RaceResult[];
  focus_recommendations: FocusRecommendation[];
  events_last_30_days: number;
  improvement_trend: 'improving' | 'stable' | 'declining' | null;
  calculated_at: string;
  created_at: string;
  updated_at: string;
}

// ============================================
// Type Mappers
// ============================================

/**
 * Convert database row to RaceChecklistItem
 */
export function mapRowToChecklistItem(row: RaceChecklistItemRow): RaceChecklistItem {
  return {
    id: row.id,
    sailorId: row.sailor_id,
    raceEventId: row.race_event_id,
    phase: row.phase,
    category: row.category as ChecklistCategory,
    title: row.title,
    description: row.description || undefined,
    status: row.status,
    completedAt: row.completed_at || undefined,
    outcomeRating: row.outcome_rating || undefined,
    outcomeNotes: row.outcome_notes || undefined,
    source: row.source,
    sourceLearningEventId: row.source_learning_event_id || undefined,
    isPersonalized: row.is_personalized,
    personalizationReason: row.personalization_reason || undefined,
    confidenceScore: row.confidence_score || undefined,
    templateItemId: row.template_item_id || undefined,
    sortOrder: row.sort_order,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/**
 * Convert database row to ExcellenceMetrics
 */
export function mapRowToExcellenceMetrics(row: ExcellenceMetricsRow): ExcellenceMetrics {
  return {
    id: row.id,
    sailorId: row.sailor_id,
    seasonId: row.season_id || undefined,
    phaseMastery: {
      prep: row.prep_mastery,
      launch: row.launch_mastery,
      start: row.start_mastery,
      upwind: row.upwind_mastery,
      downwind: row.downwind_mastery,
      markRounding: row.mark_rounding_mastery,
      finish: row.finish_mastery,
      review: row.review_mastery,
    },
    frameworkScores: row.framework_scores,
    outcomes: {
      racesCompleted: row.races_completed,
      averagePosition: row.average_position || 0,
      positionTrend: row.position_trend || 'stable',
      bestFinish: row.best_finish || 0,
      bestFinishRaceId: row.best_finish_race_id || undefined,
      recentResults: row.recent_results,
    },
    focusRecommendations: row.focus_recommendations,
    eventsLast30Days: row.events_last_30_days,
    improvementTrend: row.improvement_trend || 'stable',
    calculatedAt: row.calculated_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}
