/**
 * Demo data for the Connect tab per interest.
 *
 * Provides realistic peer suggestions, communities, and discussion posts
 * for each non-sailing interest. Sailing uses live data from the database;
 * other interests use this seed data until backend support is added.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DemoPeer {
  id: string;
  name: string;
  subtitle: string;
  avatarInitials: string;
  avatarColor: string;
  stat: string;
  isFollowing: boolean;
}

export interface DemoCommunity {
  id: string;
  name: string;
  description: string;
  memberCount: number;
  icon: string; // Ionicons name
  iconColor: string;
  iconBgColor: string;
  postCount: number;
}

export interface DemoComment {
  id: string;
  authorName: string;
  authorInitials: string;
  authorColor: string;
  body: string;
  timeAgo: string;
  upvotes: number;
}

export interface DemoPost {
  id: string;
  communityName: string;
  authorName: string;
  authorInitials: string;
  authorColor: string;
  title: string;
  body: string;
  postType: 'tip' | 'question' | 'discussion' | 'safety_alert';
  topicTags: { label: string; color: string }[];
  upvotes: number;
  commentCount: number;
  viewCount: number;
  timeAgo: string;
  comments?: DemoComment[];
}

export interface InterestConnectData {
  peers: DemoPeer[];
  communities: DemoCommunity[];
  posts: DemoPost[];
  /** Label for the peers section header (e.g., "Nurses to Follow") */
  peersHeader: string;
  /** Placeholder for search (e.g., "Search nurses") */
  searchPlaceholder: string;
}

// ---------------------------------------------------------------------------
// Nursing
// ---------------------------------------------------------------------------

const NURSING_DATA: InterestConnectData = {
  peersHeader: 'Classmates & Preceptors',
  searchPlaceholder: 'Search cohort',
  peers: [
    {
      id: 'nurse-1',
      name: 'Maria Santos',
      subtitle: 'Preceptor · CCRN, MSN · Hopkins ICU',
      avatarInitials: 'MS',
      avatarColor: '#6366F1',
      stat: '12 students mentored',
      isFollowing: false,
    },
    {
      id: 'nurse-2',
      name: 'James Rodriguez',
      subtitle: 'MSN Cohort \'26 · Adult-Gero CNS track',
      avatarInitials: 'JR',
      avatarColor: '#DC2626',
      stat: '38 clinicals logged',
      isFollowing: false,
    },
    {
      id: 'nurse-3',
      name: 'Emily Watson',
      subtitle: 'MSN Cohort \'26 · Pediatric NP track',
      avatarInitials: 'EW',
      avatarColor: '#059669',
      stat: '42 clinicals logged',
      isFollowing: false,
    },
    {
      id: 'nurse-4',
      name: 'Aisha Patel',
      subtitle: 'MSN Cohort \'26 · Family NP track',
      avatarInitials: 'AP',
      avatarColor: '#D97706',
      stat: '35 clinicals logged',
      isFollowing: false,
    },
    {
      id: 'nurse-5',
      name: 'Marcus Thompson',
      subtitle: 'Preceptor · CRNA · Hopkins Bayview',
      avatarInitials: 'MT',
      avatarColor: '#7C3AED',
      stat: '8 students mentored',
      isFollowing: false,
    },
    {
      id: 'nurse-6',
      name: 'Rachel Kim',
      subtitle: 'MSN Cohort \'26 · Nurse-Midwifery track',
      avatarInitials: 'RK',
      avatarColor: '#EC4899',
      stat: '29 clinicals logged',
      isFollowing: false,
    },
    {
      id: 'nurse-7',
      name: 'Dr. Linda Rojas',
      subtitle: 'Faculty · DNP · Clinical Coordinator',
      avatarInitials: 'LR',
      avatarColor: '#0891B2',
      stat: 'JHU SON Faculty',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-nursing-1',
      name: 'JHU MSN Cohort \'26',
      description: 'Your cohort hub — rotation swaps, study sessions, shared notes, and moral support.',
      memberCount: 86,
      icon: 'school-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 312,
    },
    {
      id: 'comm-nursing-2',
      name: 'Evidence-Based Practice',
      description: 'Discuss research appraisal, PICOT questions, and implementing evidence in clinical rotations.',
      memberCount: 420,
      icon: 'document-text-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 178,
    },
    {
      id: 'comm-nursing-3',
      name: 'Clinical Rotation Tips',
      description: 'What to expect at each site, preceptor advice, and how to get the most out of your hours.',
      memberCount: 1640,
      icon: 'compass-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 534,
    },
    {
      id: 'comm-nursing-4',
      name: 'Advanced Pharm',
      description: 'Drug interactions, prescribing nuances, and pharmacology study resources for NP students.',
      memberCount: 980,
      icon: 'flask-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 245,
    },
    {
      id: 'comm-nursing-5',
      name: 'Certification & Boards Prep',
      description: 'ANCC, AANP, and specialty cert study strategies, question banks, and exam day tips.',
      memberCount: 3200,
      icon: 'ribbon-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 890,
    },
    {
      id: 'comm-nursing-6',
      name: 'Patient Safety & Quality',
      description: 'Near-miss reporting, root cause analysis, and quality improvement project ideas.',
      memberCount: 740,
      icon: 'shield-checkmark-outline',
      iconColor: '#0891B2',
      iconBgColor: '#CFFAFE',
      postCount: 156,
    },
  ],
  posts: [
    {
      id: 'post-nursing-1',
      communityName: 'JHU MSN Cohort \'26',
      authorName: 'Aisha Patel',
      authorInitials: 'AP',
      authorColor: '#D97706',
      title: 'Anyone rotating at Sibley Memorial next block? Let\'s coordinate schedules',
      body: 'I just got my Spring placement at Sibley for my FNP clinical hours. Would love to connect with anyone else placed there — we can share parking tips, preceptor intel, and study together between patients.',
      postType: 'discussion',
      topicTags: [
        { label: 'Rotation Planning', color: '#2563EB' },
        { label: 'Cohort \'26', color: '#6366F1' },
      ],
      upvotes: 24,
      commentCount: 11,
      viewCount: 78,
      timeAgo: '2h ago',
      comments: [
        { id: 'c-n1-1', authorName: 'Emily Watson', authorInitials: 'EW', authorColor: '#059669', body: 'I\'m at Sibley too! Peds NP track, starting in March. Let\'s definitely coordinate — the parking garage on the south side is free before 7am.', timeAgo: '1h ago', upvotes: 8 },
        { id: 'c-n1-2', authorName: 'James Rodriguez', authorInitials: 'JR', authorColor: '#DC2626', body: 'I was there last semester. Ask for Dr. Pham as your preceptor if you can — she\'s incredible and lets students run the assessment independently.', timeAgo: '45m ago', upvotes: 14 },
        { id: 'c-n1-3', authorName: 'Rachel Kim', authorInitials: 'RK', authorColor: '#EC4899', body: 'Not at Sibley but I\'m at Suburban — close enough for study sessions! DM me.', timeAgo: '30m ago', upvotes: 3 },
      ],
    },
    {
      id: 'post-nursing-2',
      communityName: 'Evidence-Based Practice',
      authorName: 'Emily Watson',
      authorInitials: 'EW',
      authorColor: '#059669',
      title: 'PICOT framework for my capstone: feedback on my clinical question?',
      body: 'Working on my DNP capstone proposal. My PICOT: "In hospitalized pediatric patients (P), does nurse-led family education using teach-back (I) compared to standard discharge instructions (C) reduce 30-day readmission rates (O) within 6 months (T)?" Thoughts on feasibility?',
      postType: 'question',
      topicTags: [
        { label: 'Capstone', color: '#7C3AED' },
        { label: 'Research', color: '#059669' },
      ],
      upvotes: 38,
      commentCount: 16,
      viewCount: 290,
      timeAgo: '4h ago',
      comments: [
        { id: 'c-n2-1', authorName: 'Dr. Linda Rojas', authorInitials: 'LR', authorColor: '#0891B2', body: 'Good PICOT structure, Emily. Consider narrowing "hospitalized" to a specific unit (e.g., general peds) — it\'ll make your data collection much more feasible for the capstone timeline.', timeAgo: '3h ago', upvotes: 22 },
        { id: 'c-n2-2', authorName: 'Maria Santos', authorInitials: 'MS', authorColor: '#6366F1', body: 'Teach-back is a great intervention. We use it in the ICU and readmission data is easy to pull from Epic. Happy to connect you with our QI team.', timeAgo: '2h ago', upvotes: 11 },
      ],
    },
    {
      id: 'post-nursing-3',
      communityName: 'Clinical Rotation Tips',
      authorName: 'Maria Santos',
      authorInitials: 'MS',
      authorColor: '#6366F1',
      title: 'Preceptor perspective: what makes an MSN student stand out on day one',
      body: 'After mentoring 12 grad students, here\'s what separates the ones who thrive: come with 3 learning goals written down, review your patient list the night before, and ask "Can I try that?" instead of waiting to be invited. The students who own their learning get the best experiences.',
      postType: 'tip',
      topicTags: [
        { label: 'Preceptor Advice', color: '#6366F1' },
        { label: 'Clinical Success', color: '#059669' },
      ],
      upvotes: 142,
      commentCount: 29,
      viewCount: 1840,
      timeAgo: '1d ago',
      comments: [
        { id: 'c-n3-1', authorName: 'Aisha Patel', authorInitials: 'AP', authorColor: '#D97706', body: 'The "Can I try that?" tip is so good. I started doing this and my preceptor immediately gave me more autonomy with patient assessments.', timeAgo: '20h ago', upvotes: 34 },
        { id: 'c-n3-2', authorName: 'Rachel Kim', authorInitials: 'RK', authorColor: '#EC4899', body: 'Writing down 3 learning goals changed everything for me. It gives the preceptor something concrete to work with instead of "what do you want to learn today?"', timeAgo: '18h ago', upvotes: 28 },
        { id: 'c-n3-3', authorName: 'James Rodriguez', authorInitials: 'JR', authorColor: '#DC2626', body: 'Also — review your patients the night before if your preceptor sends the list. Showing up knowing the meds and history makes a huge impression.', timeAgo: '16h ago', upvotes: 19 },
      ],
    },
    {
      id: 'post-nursing-4',
      communityName: 'Advanced Pharm',
      authorName: 'James Rodriguez',
      authorInitials: 'JR',
      authorColor: '#DC2626',
      title: 'Warfarin vs. DOACs decision tree — made a study sheet',
      body: 'Struggling with the anticoagulation prescribing decisions for our pharm final. Made a one-page decision tree covering when to use warfarin vs. apixaban vs. rivaroxaban based on indication, renal function, and drug interactions. Happy to share.',
      postType: 'tip',
      topicTags: [
        { label: 'Pharmacology', color: '#DC2626' },
        { label: 'Study Resources', color: '#2563EB' },
      ],
      upvotes: 67,
      commentCount: 21,
      viewCount: 580,
      timeAgo: '1d ago',
      comments: [
        { id: 'c-n4-1', authorName: 'Emily Watson', authorInitials: 'EW', authorColor: '#059669', body: 'Please share! I\'m drowning in the anticoag section. The renal dosing adjustments alone are a nightmare.', timeAgo: '22h ago', upvotes: 9 },
        { id: 'c-n4-2', authorName: 'Marcus Thompson', authorInitials: 'MT', authorColor: '#7C3AED', body: 'Great resource, James. One thing to add — always check for heparin-induced thrombocytopenia history before bridging. It\'s a common miss on boards.', timeAgo: '20h ago', upvotes: 15 },
      ],
    },
    {
      id: 'post-nursing-5',
      communityName: 'Patient Safety & Quality',
      authorName: 'Dr. Linda Rojas',
      authorInitials: 'LR',
      authorColor: '#0891B2',
      title: 'Reminder: near-miss reporting is learning, not blame — use your BetterAt logs',
      body: 'A student flagged a near-miss during clinical this week and it led to a real process improvement at the site. This is exactly how QI works. Document what you see in your clinical debrief — your observations as students are incredibly valuable because you notice things the unit has normalized.',
      postType: 'safety_alert',
      topicTags: [
        { label: 'Patient Safety', color: '#DC2626' },
        { label: 'Quality Improvement', color: '#0891B2' },
      ],
      upvotes: 94,
      commentCount: 13,
      viewCount: 720,
      timeAgo: '2d ago',
      comments: [
        { id: 'c-n5-1', authorName: 'Aisha Patel', authorInitials: 'AP', authorColor: '#D97706', body: 'That was me who reported it! My preceptor helped me write it up as a QI case study. It\'s now part of my clinical portfolio. So glad I spoke up.', timeAgo: '1d ago', upvotes: 42 },
        { id: 'c-n5-2', authorName: 'Maria Santos', authorInitials: 'MS', authorColor: '#6366F1', body: 'As a preceptor, I want to emphasize — we WANT students to report. Fresh eyes catch things we\'ve become blind to. It\'s not tattling, it\'s patient advocacy.', timeAgo: '1d ago', upvotes: 31 },
      ],
    },
    {
      id: 'post-nursing-6',
      communityName: 'Certification & Boards Prep',
      authorName: 'Rachel Kim',
      authorInitials: 'RK',
      authorColor: '#EC4899',
      title: 'Passed ANCC FNP boards on first attempt — here\'s my 8-week study plan',
      body: 'Just got my results back — passed! Used a combo of Leik review, Fitzgerald audio, and the APEA predictor exams. The biggest game changer was doing 75 practice questions every single day for the last 4 weeks. Full breakdown of my schedule inside.',
      postType: 'tip',
      topicTags: [
        { label: 'ANCC', color: '#D97706' },
        { label: 'Study Plan', color: '#2563EB' },
      ],
      upvotes: 218,
      commentCount: 47,
      viewCount: 4100,
      timeAgo: '3d ago',
      comments: [
        { id: 'c-n6-1', authorName: 'Emily Watson', authorInitials: 'EW', authorColor: '#059669', body: 'Rachel this is incredibly helpful! Did you do the Fitzgerald live review or just the audio? Trying to decide if the live session is worth the $$$.', timeAgo: '2d ago', upvotes: 18 },
        { id: 'c-n6-2', authorName: 'Rachel Kim', authorInitials: 'RK', authorColor: '#EC4899', body: 'Just the audio — saved $400 and honestly it was enough. Pair it with Leik for the content gaps. The APEA predictor is the real secret weapon though.', timeAgo: '2d ago', upvotes: 26 },
        { id: 'c-n6-3', authorName: 'James Rodriguez', authorInitials: 'JR', authorColor: '#DC2626', body: 'Congrats Rachel! How did you handle the pharm section? That\'s where I\'m weakest.', timeAgo: '2d ago', upvotes: 7 },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------

const DRAWING_DATA: InterestConnectData = {
  peersHeader: 'Artists to Follow',
  searchPlaceholder: 'Search artists',
  peers: [
    {
      id: 'artist-1',
      name: 'Maya Patel',
      subtitle: 'Digital Illustration · Concept Art',
      avatarInitials: 'MP',
      avatarColor: '#7C3AED',
      stat: '180 sessions logged',
      isFollowing: false,
    },
    {
      id: 'artist-2',
      name: 'Lucas Rivera',
      subtitle: 'Charcoal & Graphite · Portraits',
      avatarInitials: 'LR',
      avatarColor: '#374151',
      stat: '240 sessions logged',
      isFollowing: false,
    },
    {
      id: 'artist-3',
      name: 'Sophie Turner',
      subtitle: 'Watercolor · Landscapes',
      avatarInitials: 'ST',
      avatarColor: '#2563EB',
      stat: '310 sessions logged',
      isFollowing: false,
    },
    {
      id: 'artist-4',
      name: 'Kenji Tanaka',
      subtitle: 'Ink & Pen · Urban Sketching',
      avatarInitials: 'KT',
      avatarColor: '#059669',
      stat: '420 sessions logged',
      isFollowing: false,
    },
    {
      id: 'artist-5',
      name: 'Olivia Chen',
      subtitle: 'Oil Painting · Still Life',
      avatarInitials: 'OC',
      avatarColor: '#D97706',
      stat: '150 sessions logged',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-drawing-1',
      name: 'Portrait Fundamentals',
      description: 'Anatomy, proportion, and likeness. Share studies, get feedback on portraits.',
      memberCount: 2800,
      icon: 'person-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 198,
    },
    {
      id: 'comm-drawing-2',
      name: 'Daily Sketch Challenge',
      description: 'A new prompt every day. Post your sketch, see what others created.',
      memberCount: 4500,
      icon: 'brush-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 1240,
    },
    {
      id: 'comm-drawing-3',
      name: 'Digital Art Tools',
      description: 'Procreate, Clip Studio, Photoshop — tips, brushes, and workflow discussions.',
      memberCount: 3200,
      icon: 'tablet-portrait-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 340,
    },
    {
      id: 'comm-drawing-4',
      name: 'Critique Circle',
      description: 'Constructive feedback on your work. Post a piece, receive thoughtful critique.',
      memberCount: 1600,
      icon: 'chatbubble-ellipses-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 890,
    },
    {
      id: 'comm-drawing-5',
      name: 'Reference & Inspiration',
      description: 'Share reference photos, inspiring artwork, and creative prompts.',
      memberCount: 5200,
      icon: 'image-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 670,
    },
  ],
  posts: [
    {
      id: 'post-drawing-1',
      communityName: 'Portrait Fundamentals',
      authorName: 'Lucas Rivera',
      authorInitials: 'LR',
      authorColor: '#374151',
      title: 'The Loomis method vs. Reilly abstraction — which do you prefer for head construction?',
      body: 'I\'ve been using Loomis for years but recently tried the Reilly method and found it helps me capture gesture better. Curious what others prefer and why.',
      postType: 'discussion',
      topicTags: [
        { label: 'Anatomy', color: '#7C3AED' },
        { label: 'Technique', color: '#2563EB' },
      ],
      upvotes: 62,
      commentCount: 28,
      viewCount: 940,
      timeAgo: '3h ago',
      comments: [
        { id: 'c-d1-1', authorName: 'Sophie Turner', authorInitials: 'ST', authorColor: '#2563EB', body: 'I switched to Reilly last year and it really helped with gesture. Loomis is great for static poses but Reilly captures movement better IMO.', timeAgo: '2h ago', upvotes: 14 },
        { id: 'c-d1-2', authorName: 'Kenji Tanaka', authorInitials: 'KT', authorColor: '#059669', body: 'I use a hybrid — Loomis for the basic form, then Reilly rhythms for the features. Best of both worlds.', timeAgo: '1h ago', upvotes: 21 },
      ],
    },
    {
      id: 'post-drawing-2',
      communityName: 'Daily Sketch Challenge',
      authorName: 'Maya Patel',
      authorInitials: 'MP',
      authorColor: '#7C3AED',
      title: 'Day 47: "Morning Light" — 30 minute study',
      body: 'Tried to capture the warm light through my kitchen window hitting the fruit bowl. Focused on keeping values simple — only 3 value groups.',
      postType: 'discussion',
      topicTags: [
        { label: 'Daily Sketch', color: '#D97706' },
        { label: 'Values', color: '#059669' },
      ],
      upvotes: 34,
      commentCount: 8,
      viewCount: 420,
      timeAgo: '6h ago',
    },
    {
      id: 'post-drawing-3',
      communityName: 'Digital Art Tools',
      authorName: 'Kenji Tanaka',
      authorInitials: 'KT',
      authorColor: '#059669',
      title: 'Custom brush set for architectural sketching in Procreate',
      body: 'I made a set of 6 brushes that simulate technical pens and felt tips. They\'re great for urban sketching with clean line weights. Free download link inside.',
      postType: 'tip',
      topicTags: [
        { label: 'Procreate', color: '#2563EB' },
        { label: 'Brushes', color: '#374151' },
      ],
      upvotes: 108,
      commentCount: 19,
      viewCount: 2100,
      timeAgo: '1d ago',
    },
    {
      id: 'post-drawing-4',
      communityName: 'Critique Circle',
      authorName: 'Sophie Turner',
      authorInitials: 'ST',
      authorColor: '#2563EB',
      title: 'Feedback request: watercolor landscape — struggling with atmospheric perspective',
      body: 'The foreground feels right but my background mountains keep looking too saturated and don\'t recede. I\'ve tried diluting more but lose detail. Any suggestions?',
      postType: 'question',
      topicTags: [
        { label: 'Watercolor', color: '#2563EB' },
        { label: 'Critique', color: '#DC2626' },
      ],
      upvotes: 22,
      commentCount: 14,
      viewCount: 380,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Fitness
// ---------------------------------------------------------------------------

const FITNESS_DATA: InterestConnectData = {
  peersHeader: 'Athletes to Follow',
  searchPlaceholder: 'Search athletes',
  peers: [
    {
      id: 'athlete-1',
      name: 'Alex Turner',
      subtitle: 'Strength Training · Powerlifting',
      avatarInitials: 'AT',
      avatarColor: '#DC2626',
      stat: '520 workouts logged',
      isFollowing: false,
    },
    {
      id: 'athlete-2',
      name: 'Jordan Kim',
      subtitle: 'Distance Running · Marathon',
      avatarInitials: 'JK',
      avatarColor: '#2563EB',
      stat: '380 workouts logged',
      isFollowing: false,
    },
    {
      id: 'athlete-3',
      name: 'Sofia Martinez',
      subtitle: 'CrossFit · HIIT',
      avatarInitials: 'SM',
      avatarColor: '#D97706',
      stat: '290 workouts logged',
      isFollowing: false,
    },
    {
      id: 'athlete-4',
      name: 'Ryan Okafor',
      subtitle: 'Calisthenics · Bodyweight',
      avatarInitials: 'RO',
      avatarColor: '#059669',
      stat: '440 workouts logged',
      isFollowing: false,
    },
    {
      id: 'athlete-5',
      name: 'Mia Chang',
      subtitle: 'Yoga · Mobility',
      avatarInitials: 'MC',
      avatarColor: '#7C3AED',
      stat: '610 workouts logged',
      isFollowing: false,
    },
    {
      id: 'athlete-6',
      name: 'Chris Hensley',
      subtitle: 'Olympic Lifting · Strength',
      avatarInitials: 'CH',
      avatarColor: '#374151',
      stat: '350 workouts logged',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-fitness-1',
      name: 'Strength & Power',
      description: 'Programming, form checks, and PR celebrations for lifters of all levels.',
      memberCount: 4200,
      icon: 'barbell-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 890,
    },
    {
      id: 'comm-fitness-2',
      name: 'Running Community',
      description: 'Training plans, race reports, and gear reviews for runners.',
      memberCount: 6100,
      icon: 'walk-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 1340,
    },
    {
      id: 'comm-fitness-3',
      name: 'Nutrition & Recovery',
      description: 'Meal prep ideas, supplement discussions, and recovery protocols.',
      memberCount: 3800,
      icon: 'nutrition-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 420,
    },
    {
      id: 'comm-fitness-4',
      name: 'Form Check',
      description: 'Post videos for form feedback. Prevent injuries, lift better.',
      memberCount: 2900,
      icon: 'videocam-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 780,
    },
    {
      id: 'comm-fitness-5',
      name: 'Injury Prevention',
      description: 'Mobility work, prehab exercises, and coming back from injuries.',
      memberCount: 1800,
      icon: 'bandage-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 210,
    },
  ],
  posts: [
    {
      id: 'post-fitness-1',
      communityName: 'Strength & Power',
      authorName: 'Alex Turner',
      authorInitials: 'AT',
      authorColor: '#DC2626',
      title: 'Hit a 200kg deadlift PR after switching to sumo — here\'s what changed',
      body: 'After 2 years stuck at 185kg conventional, I switched to sumo 6 months ago. The key wasn\'t just the stance — it was the hip mobility work I had to do first.',
      postType: 'discussion',
      topicTags: [
        { label: 'Deadlift', color: '#DC2626' },
        { label: 'PR', color: '#D97706' },
      ],
      upvotes: 124,
      commentCount: 38,
      viewCount: 2800,
      timeAgo: '4h ago',
      comments: [
        { id: 'c-f1-1', authorName: 'Chris Hensley', authorInitials: 'CH', authorColor: '#374151', body: 'How long did it take to adjust? I tried sumo once and my hips were screaming for a week.', timeAgo: '3h ago', upvotes: 8 },
        { id: 'c-f1-2', authorName: 'Alex Turner', authorInitials: 'AT', authorColor: '#DC2626', body: 'Honestly about 3 weeks of feeling weak. The 90/90 hip stretch and frog stretch daily made the biggest difference. Stick with it!', timeAgo: '2h ago', upvotes: 19 },
      ],
    },
    {
      id: 'post-fitness-2',
      communityName: 'Running Community',
      authorName: 'Jordan Kim',
      authorInitials: 'JK',
      authorColor: '#2563EB',
      title: 'Sub-3:30 marathon training plan — 16 weeks, 5 days/week',
      body: 'Sharing the plan that got me from 3:45 to 3:28. Key insight: the 80/20 easy/hard split is real. I was running too fast on easy days for years.',
      postType: 'tip',
      topicTags: [
        { label: 'Marathon', color: '#2563EB' },
        { label: 'Training Plan', color: '#059669' },
      ],
      upvotes: 89,
      commentCount: 22,
      viewCount: 1900,
      timeAgo: '8h ago',
    },
    {
      id: 'post-fitness-3',
      communityName: 'Form Check',
      authorName: 'Sofia Martinez',
      authorInitials: 'SM',
      authorColor: '#D97706',
      title: 'Squat form check — is my butt wink a problem at this depth?',
      body: 'I\'ve been told I have butt wink at the bottom of my squat but I\'m not sure if it\'s actually causing issues. Currently squatting 100kg pain-free.',
      postType: 'question',
      topicTags: [
        { label: 'Squat', color: '#DC2626' },
        { label: 'Form Check', color: '#D97706' },
      ],
      upvotes: 45,
      commentCount: 31,
      viewCount: 1200,
      timeAgo: '1d ago',
    },
    {
      id: 'post-fitness-4',
      communityName: 'Injury Prevention',
      authorName: 'Mia Chang',
      authorInitials: 'MC',
      authorColor: '#7C3AED',
      title: 'Shoulder impingement: the 3 exercises that fixed mine',
      body: 'After 4 months of shoulder pain during overhead pressing, these 3 exercises from my physio completely resolved it. Face pulls, band pull-aparts, and...',
      postType: 'tip',
      topicTags: [
        { label: 'Rehab', color: '#7C3AED' },
        { label: 'Shoulders', color: '#2563EB' },
      ],
      upvotes: 201,
      commentCount: 44,
      viewCount: 4200,
      timeAgo: '2d ago',
    },
    {
      id: 'post-fitness-5',
      communityName: 'Nutrition & Recovery',
      authorName: 'Ryan Okafor',
      authorInitials: 'RO',
      authorColor: '#059669',
      title: 'Creatine timing: does it actually matter?',
      body: 'I\'ve been taking creatine post-workout for years but just read a study saying timing doesn\'t matter. Anyone notice a difference?',
      postType: 'question',
      topicTags: [
        { label: 'Supplements', color: '#059669' },
        { label: 'Recovery', color: '#7C3AED' },
      ],
      upvotes: 56,
      commentCount: 29,
      viewCount: 1600,
      timeAgo: '2d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Knitting
// ---------------------------------------------------------------------------

const KNITTING_DATA: InterestConnectData = {
  peersHeader: 'Knitters to Follow',
  searchPlaceholder: 'Search knitters',
  peers: [
    {
      id: 'knitter-1',
      name: 'Hannah Birch',
      subtitle: 'Colorwork & Fair Isle · Sweaters',
      avatarInitials: 'HB',
      avatarColor: '#7C3AED',
      stat: '48 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-2',
      name: 'Clara Nguyen',
      subtitle: 'Lace Knitting · Shawls',
      avatarInitials: 'CN',
      avatarColor: '#EC4899',
      stat: '62 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-3',
      name: 'Ruth Andersen',
      subtitle: 'Sock Knitting · Accessories',
      avatarInitials: 'RA',
      avatarColor: '#059669',
      stat: '91 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-4',
      name: 'Tom Weaver',
      subtitle: 'Cable Knitting · Aran Sweaters',
      avatarInitials: 'TW',
      avatarColor: '#2563EB',
      stat: '35 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-5',
      name: 'Margot Ellis',
      subtitle: 'Brioche · Two-Color Knitting',
      avatarInitials: 'ME',
      avatarColor: '#D97706',
      stat: '44 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-6',
      name: 'Yuki Sato',
      subtitle: 'Japanese Knitting · Amigurumi',
      avatarInitials: 'YS',
      avatarColor: '#DC2626',
      stat: '73 projects completed',
      isFollowing: false,
    },
    {
      id: 'knitter-7',
      name: 'Diane Okafor',
      subtitle: 'Garment Construction · Sweater Design',
      avatarInitials: 'DO',
      avatarColor: '#0891B2',
      stat: '28 patterns published',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-knit-1',
      name: 'Sock Knitters Unite',
      description: 'Toe-up, cuff-down, two-at-a-time — all sock techniques welcome. Share your latest pair.',
      memberCount: 3200,
      icon: 'footsteps-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 890,
    },
    {
      id: 'comm-knit-2',
      name: 'Colorwork & Fair Isle',
      description: 'Stranded colorwork, intarsia, and Fair Isle patterns. Tips for tension and floats.',
      memberCount: 2400,
      icon: 'color-palette-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 560,
    },
    {
      id: 'comm-knit-3',
      name: 'Yarn Stash & Reviews',
      description: 'Yarn reviews, stash organization, and finding the perfect yarn for your next project.',
      memberCount: 5100,
      icon: 'pricetag-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 1240,
    },
    {
      id: 'comm-knit-4',
      name: 'Beginner Knitters',
      description: 'No question too basic. Learn cast-on, knit, purl, and build confidence stitch by stitch.',
      memberCount: 4800,
      icon: 'sparkles-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 2100,
    },
    {
      id: 'comm-knit-5',
      name: 'Sweater Workshop',
      description: 'Top-down, bottom-up, seamed or seamless. Share WIPs and get fit advice.',
      memberCount: 1800,
      icon: 'shirt-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 420,
    },
    {
      id: 'comm-knit-6',
      name: 'Knit-Alongs',
      description: 'Active KALs, pattern discussions, and progress check-ins. Knit together, apart.',
      memberCount: 2600,
      icon: 'people-outline',
      iconColor: '#EC4899',
      iconBgColor: '#FCE7F3',
      postCount: 780,
    },
  ],
  posts: [
    {
      id: 'post-knit-1',
      communityName: 'Sock Knitters Unite',
      authorName: 'Ruth Andersen',
      authorInitials: 'RA',
      authorColor: '#059669',
      title: 'Finally nailed the afterthought heel — here\'s my trick for avoiding holes',
      body: 'After 20+ pairs with flap-and-gusset, I tried afterthought heels and kept getting holes at the pickup points. The fix: pick up one extra stitch on each side, then k2tog on the next round. Zero holes.',
      postType: 'tip',
      topicTags: [
        { label: 'Socks', color: '#7C3AED' },
        { label: 'Technique', color: '#059669' },
      ],
      upvotes: 87,
      commentCount: 23,
      viewCount: 1200,
      timeAgo: '3h ago',
      comments: [
        { id: 'c-k1-1', authorName: 'Clara Nguyen', authorInitials: 'CN', authorColor: '#EC4899', body: 'This is exactly what I needed! I gave up on afterthought heels after too many holes. Trying this on my next pair.', timeAgo: '2h ago', upvotes: 12 },
        { id: 'c-k1-2', authorName: 'Tom Weaver', authorInitials: 'TW', authorColor: '#2563EB', body: 'I do something similar but with a crochet provisional cast-on. Keeps it really tidy. Great tip!', timeAgo: '1h ago', upvotes: 8 },
      ],
    },
    {
      id: 'post-knit-2',
      communityName: 'Colorwork & Fair Isle',
      authorName: 'Hannah Birch',
      authorInitials: 'HB',
      authorColor: '#7C3AED',
      title: 'Managing float tension in Fair Isle — do you trap or not?',
      body: 'I\'m working on a yoke sweater with long floats (7+ stitches). I trap my floats every 3-4 stitches but I can see them showing through on the right side with lighter colors. Anyone have tips for trapping without show-through?',
      postType: 'question',
      topicTags: [
        { label: 'Fair Isle', color: '#DC2626' },
        { label: 'Tension', color: '#2563EB' },
      ],
      upvotes: 54,
      commentCount: 31,
      viewCount: 940,
      timeAgo: '5h ago',
      comments: [
        { id: 'c-k2-1', authorName: 'Diane Okafor', authorInitials: 'DO', authorColor: '#0891B2', body: 'Try trapping on the purl bumps only — if you trap on the smooth V side, the carried yarn peeks through. Also, going up a needle size for colorwork sections helps.', timeAgo: '4h ago', upvotes: 19 },
        { id: 'c-k2-2', authorName: 'Yuki Sato', authorInitials: 'YS', authorColor: '#DC2626', body: 'In Japanese knitting books they recommend not trapping at all — just keep floats loose. I use a yarn guide on my left hand and it keeps tension even without trapping.', timeAgo: '3h ago', upvotes: 24 },
      ],
    },
    {
      id: 'post-knit-3',
      communityName: 'Yarn Stash & Reviews',
      authorName: 'Margot Ellis',
      authorInitials: 'ME',
      authorColor: '#D97706',
      title: 'Honest review: is Malabrigo Rios worth the hype?',
      body: 'I see Rios recommended everywhere for sweaters. Just finished my first skein — the hand is incredible but I noticed slight pooling in the variegated colorway. Has anyone had pilling issues after wearing? Considering it for a full sweater quantity.',
      postType: 'discussion',
      topicTags: [
        { label: 'Yarn Review', color: '#D97706' },
        { label: 'Sweater Yarn', color: '#2563EB' },
      ],
      upvotes: 92,
      commentCount: 41,
      viewCount: 2800,
      timeAgo: '1d ago',
      comments: [
        { id: 'c-k3-1', authorName: 'Hannah Birch', authorInitials: 'HB', authorColor: '#7C3AED', body: 'I\'ve knit 3 sweaters in Rios. It pills a bit the first few wears but then stops. The colors are unbeatable. For pooling, try alternating skeins every 2 rows.', timeAgo: '20h ago', upvotes: 28 },
        { id: 'c-k3-2', authorName: 'Ruth Andersen', authorInitials: 'RA', authorColor: '#059669', body: 'Love Rios for socks too — surprisingly durable for a superwash merino. The semi-solids are gorgeous.', timeAgo: '18h ago', upvotes: 15 },
      ],
    },
    {
      id: 'post-knit-4',
      communityName: 'Beginner Knitters',
      authorName: 'Tom Weaver',
      authorInitials: 'TW',
      authorColor: '#2563EB',
      title: 'Just finished my first cable project and it actually looks like cables!',
      body: 'I was so intimidated by cables but they\'re honestly just moving stitches around. Started with a simple 6-stitch rope cable scarf and I\'m hooked. Already planning a cabled hat. The cable needle feels awkward though — any tips?',
      postType: 'discussion',
      topicTags: [
        { label: 'Cables', color: '#2563EB' },
        { label: 'Beginner Win', color: '#059669' },
      ],
      upvotes: 156,
      commentCount: 28,
      viewCount: 3200,
      timeAgo: '1d ago',
      comments: [
        { id: 'c-k4-1', authorName: 'Diane Okafor', authorInitials: 'DO', authorColor: '#0891B2', body: 'Try cabling without a cable needle! For small cables (4-6 stitches), just pinch the stitches and slip them off, then put them back. Game changer.', timeAgo: '22h ago', upvotes: 42 },
        { id: 'c-k4-2', authorName: 'Margot Ellis', authorInitials: 'ME', authorColor: '#D97706', body: 'Congrats! That first cable moment is magical. If the cable needle is annoying, a DPN one size smaller works great too.', timeAgo: '20h ago', upvotes: 18 },
      ],
    },
    {
      id: 'post-knit-5',
      communityName: 'Sweater Workshop',
      authorName: 'Diane Okafor',
      authorInitials: 'DO',
      authorColor: '#0891B2',
      title: 'Top-down raglan fit guide: how to check your yoke depth before committing',
      body: 'The most common mistake I see in top-down raglans is separating the body too early or too late. Here\'s my quick check: try it on (or measure flat) when you think you\'re close. The raglan line should end about 1" below your armpit. If it\'s at your armpit, you need 4-6 more rows.',
      postType: 'tip',
      topicTags: [
        { label: 'Sweater Fit', color: '#0891B2' },
        { label: 'Construction', color: '#7C3AED' },
      ],
      upvotes: 198,
      commentCount: 36,
      viewCount: 4100,
      timeAgo: '2d ago',
      comments: [
        { id: 'c-k5-1', authorName: 'Hannah Birch', authorInitials: 'HB', authorColor: '#7C3AED', body: 'This would have saved me frogging an entire yoke last month. I separated way too early and the armholes were tiny. Bookmarking this.', timeAgo: '1d ago', upvotes: 31 },
        { id: 'c-k5-2', authorName: 'Clara Nguyen', authorInitials: 'CN', authorColor: '#EC4899', body: 'Another tip: put your body stitches on waste yarn and try on before doing the sleeves. Much easier to adjust at that point.', timeAgo: '1d ago', upvotes: 22 },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Fiber Arts
// ---------------------------------------------------------------------------

const FIBER_ARTS_DATA: InterestConnectData = {
  peersHeader: 'Fiber Artists to Follow',
  searchPlaceholder: 'Search fiber artists',
  peers: [
    {
      id: 'fiber-1',
      name: 'Amara Osei',
      subtitle: 'Weaving · Tapestry',
      avatarInitials: 'AO',
      avatarColor: '#D97706',
      stat: '34 projects completed',
      isFollowing: false,
    },
    {
      id: 'fiber-2',
      name: 'Lin Zhao',
      subtitle: 'Crochet · Amigurumi',
      avatarInitials: 'LZ',
      avatarColor: '#EC4899',
      stat: '58 projects completed',
      isFollowing: false,
    },
    {
      id: 'fiber-3',
      name: 'Petra Novak',
      subtitle: 'Spinning · Natural Dyes',
      avatarInitials: 'PN',
      avatarColor: '#059669',
      stat: '42 projects completed',
      isFollowing: false,
    },
    {
      id: 'fiber-4',
      name: 'Sam Delgado',
      subtitle: 'Macramé · Fiber Sculpture',
      avatarInitials: 'SD',
      avatarColor: '#7C3AED',
      stat: '29 projects completed',
      isFollowing: false,
    },
    {
      id: 'fiber-5',
      name: 'Elsa Bergman',
      subtitle: 'Felting · Mixed Media',
      avatarInitials: 'EB',
      avatarColor: '#2563EB',
      stat: '51 projects completed',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-fiber-1',
      name: 'Handspinning',
      description: 'Drop spindle, wheel spinning, and fiber prep. Share your handspun creations.',
      memberCount: 1800,
      icon: 'sync-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 420,
    },
    {
      id: 'comm-fiber-2',
      name: 'Weaving Studio',
      description: 'Rigid heddle, floor loom, tapestry — all weaving welcome.',
      memberCount: 1200,
      icon: 'grid-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 310,
    },
    {
      id: 'comm-fiber-3',
      name: 'Natural Dyes',
      description: 'Plant-based dyes, mordants, and color experiments on fiber and fabric.',
      memberCount: 2400,
      icon: 'leaf-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 580,
    },
    {
      id: 'comm-fiber-4',
      name: 'Crochet Circle',
      description: 'Patterns, techniques, and WIP sharing for crocheters of all levels.',
      memberCount: 4200,
      icon: 'infinite-outline',
      iconColor: '#EC4899',
      iconBgColor: '#FCE7F3',
      postCount: 1100,
    },
  ],
  posts: [
    {
      id: 'post-fiber-1',
      communityName: 'Handspinning',
      authorName: 'Petra Novak',
      authorInitials: 'PN',
      authorColor: '#059669',
      title: 'First skein from raw fleece — the process was so satisfying',
      body: 'Washed, carded, and spun a Cormo fleece I picked up at a fiber festival. The whole process from raw to finished skein took about 2 weeks of evening sessions. The yarn is rustic but incredibly soft.',
      postType: 'discussion',
      topicTags: [
        { label: 'Spinning', color: '#D97706' },
        { label: 'Fleece to Yarn', color: '#059669' },
      ],
      upvotes: 76,
      commentCount: 18,
      viewCount: 920,
      timeAgo: '4h ago',
    },
    {
      id: 'post-fiber-2',
      communityName: 'Crochet Circle',
      authorName: 'Lin Zhao',
      authorInitials: 'LZ',
      authorColor: '#EC4899',
      title: 'Amigurumi tip: invisible decrease vs regular decrease — when to use each',
      body: 'The invisible decrease gives a cleaner look on the outside, but for structural pieces (like legs that need to support weight), the regular decrease is actually stronger. Here\'s my guide for when to use which.',
      postType: 'tip',
      topicTags: [
        { label: 'Amigurumi', color: '#EC4899' },
        { label: 'Technique', color: '#2563EB' },
      ],
      upvotes: 104,
      commentCount: 22,
      viewCount: 1800,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Global Health
// ---------------------------------------------------------------------------

const GLOBAL_HEALTH_DATA: InterestConnectData = {
  peersHeader: 'Practitioners to Follow',
  searchPlaceholder: 'Search practitioners',
  peers: [
    {
      id: 'gh-1',
      name: 'Dr. Maria Reyes',
      subtitle: 'Community Health · Program Design',
      avatarInitials: 'MR',
      avatarColor: '#059669',
      stat: '12 programs led',
      isFollowing: false,
    },
    {
      id: 'gh-2',
      name: 'James Okonkwo',
      subtitle: 'Epidemiology · Data Systems',
      avatarInitials: 'JO',
      avatarColor: '#2563EB',
      stat: '8 field deployments',
      isFollowing: false,
    },
    {
      id: 'gh-3',
      name: 'Ana Lucia Mendez',
      subtitle: 'Maternal Health · CHW Training',
      avatarInitials: 'AM',
      avatarColor: '#DC2626',
      stat: '15 programs led',
      isFollowing: false,
    },
    {
      id: 'gh-4',
      name: 'David Chen',
      subtitle: 'Health Systems · Policy',
      avatarInitials: 'DC',
      avatarColor: '#7C3AED',
      stat: '6 field deployments',
      isFollowing: false,
    },
    {
      id: 'gh-5',
      name: 'Fatima Al-Rashid',
      subtitle: 'Nutrition · Food Security',
      avatarInitials: 'FA',
      avatarColor: '#D97706',
      stat: '10 programs led',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-gh-1',
      name: 'Community Health Workers',
      description: 'Training, supervision, and impact measurement for CHW programs worldwide.',
      memberCount: 2800,
      icon: 'heart-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 640,
    },
    {
      id: 'comm-gh-2',
      name: 'Program Design & M&E',
      description: 'Logic models, indicators, and monitoring frameworks for health programs.',
      memberCount: 1600,
      icon: 'analytics-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 380,
    },
    {
      id: 'comm-gh-3',
      name: 'Field Stories',
      description: 'Share experiences, challenges, and lessons learned from field work.',
      memberCount: 3400,
      icon: 'earth-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 920,
    },
  ],
  posts: [
    {
      id: 'post-gh-1',
      communityName: 'Community Health Workers',
      authorName: 'Ana Lucia Mendez',
      authorInitials: 'AM',
      authorColor: '#DC2626',
      title: 'Training CHWs in remote areas: what worked and what didn\'t',
      body: 'Just finished a 6-month CHW training program in rural Guatemala. Mobile-first training materials were essential — paper manuals got destroyed in rainy season. Biggest win: pairing new CHWs with experienced ones for the first month.',
      postType: 'discussion',
      topicTags: [
        { label: 'CHW Training', color: '#DC2626' },
        { label: 'Field Lessons', color: '#059669' },
      ],
      upvotes: 89,
      commentCount: 24,
      viewCount: 1400,
      timeAgo: '6h ago',
    },
    {
      id: 'post-gh-2',
      communityName: 'Program Design & M&E',
      authorName: 'James Okonkwo',
      authorInitials: 'JO',
      authorColor: '#2563EB',
      title: 'Simple M&E framework that actually works in low-resource settings',
      body: 'After years of overcomplicating our monitoring systems, we stripped it down to 5 core indicators tracked via WhatsApp voice notes. Data quality went up because the burden on field staff went way down.',
      postType: 'tip',
      topicTags: [
        { label: 'M&E', color: '#2563EB' },
        { label: 'Data Systems', color: '#7C3AED' },
      ],
      upvotes: 124,
      commentCount: 31,
      viewCount: 2100,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Painting & Printmaking
// ---------------------------------------------------------------------------

const PAINTING_DATA: InterestConnectData = {
  peersHeader: 'Artists to Follow',
  searchPlaceholder: 'Search artists',
  peers: [
    {
      id: 'paint-1',
      name: 'Isabel Moreno',
      subtitle: 'Oil Painting · Portraiture',
      avatarInitials: 'IM',
      avatarColor: '#DC2626',
      stat: '84 sessions logged',
      isFollowing: false,
    },
    {
      id: 'paint-2',
      name: 'Niko Petrov',
      subtitle: 'Printmaking · Linocut',
      avatarInitials: 'NP',
      avatarColor: '#374151',
      stat: '120 sessions logged',
      isFollowing: false,
    },
    {
      id: 'paint-3',
      name: 'Mei Lin',
      subtitle: 'Watercolor · Botanical',
      avatarInitials: 'ML',
      avatarColor: '#059669',
      stat: '96 sessions logged',
      isFollowing: false,
    },
    {
      id: 'paint-4',
      name: 'Andre Williams',
      subtitle: 'Acrylic · Abstract',
      avatarInitials: 'AW',
      avatarColor: '#D97706',
      stat: '150 sessions logged',
      isFollowing: false,
    },
    {
      id: 'paint-5',
      name: 'Sofia Berg',
      subtitle: 'Screen Printing · Textile',
      avatarInitials: 'SB',
      avatarColor: '#7C3AED',
      stat: '68 sessions logged',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-paint-1',
      name: 'Color Mixing Lab',
      description: 'Color theory, palette building, and mixing techniques across all media.',
      memberCount: 3200,
      icon: 'color-palette-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 680,
    },
    {
      id: 'comm-paint-2',
      name: 'Printmakers Guild',
      description: 'Relief, intaglio, screen printing — techniques, inks, and press setup.',
      memberCount: 1400,
      icon: 'layers-outline',
      iconColor: '#374151',
      iconBgColor: '#F3F4F6',
      postCount: 320,
    },
    {
      id: 'comm-paint-3',
      name: 'Plein Air Painters',
      description: 'Painting outdoors — gear, locations, and handling changing light.',
      memberCount: 2800,
      icon: 'sunny-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 540,
    },
    {
      id: 'comm-paint-4',
      name: 'Critique & Feedback',
      description: 'Post your work for constructive critique. All skill levels and media welcome.',
      memberCount: 2100,
      icon: 'chatbubble-ellipses-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 890,
    },
  ],
  posts: [
    {
      id: 'post-paint-1',
      communityName: 'Color Mixing Lab',
      authorName: 'Isabel Moreno',
      authorInitials: 'IM',
      authorColor: '#DC2626',
      title: 'Limited palette challenge: painting with just 3 colors + white',
      body: 'Tried the Zorn palette (yellow ochre, cadmium red, ivory black, white) for a portrait study. The range of skin tones you can get from just these four is incredible. Highly recommend for understanding value and temperature.',
      postType: 'tip',
      topicTags: [
        { label: 'Color Theory', color: '#DC2626' },
        { label: 'Oil Painting', color: '#D97706' },
      ],
      upvotes: 78,
      commentCount: 19,
      viewCount: 1200,
      timeAgo: '5h ago',
    },
    {
      id: 'post-paint-2',
      communityName: 'Printmakers Guild',
      authorName: 'Niko Petrov',
      authorInitials: 'NP',
      authorColor: '#374151',
      title: 'Reduction linocut: planning your layers in reverse',
      body: 'The key insight that unlocked reduction printing for me: plan your lightest areas first and cut those away before the first print. You\'re printing dark to light but cutting light to dark. A simple color map on paper saves hours of frustration.',
      postType: 'discussion',
      topicTags: [
        { label: 'Linocut', color: '#374151' },
        { label: 'Technique', color: '#059669' },
      ],
      upvotes: 62,
      commentCount: 14,
      viewCount: 880,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Lifelong Learning
// ---------------------------------------------------------------------------

const LIFELONG_LEARNING_DATA: InterestConnectData = {
  peersHeader: 'Learners to Follow',
  searchPlaceholder: 'Search learners',
  peers: [
    {
      id: 'll-1',
      name: 'Marcus Rivera',
      subtitle: 'Languages · History',
      avatarInitials: 'MR',
      avatarColor: '#2563EB',
      stat: '180 sessions logged',
      isFollowing: false,
    },
    {
      id: 'll-2',
      name: 'Priya Sharma',
      subtitle: 'Philosophy · Writing',
      avatarInitials: 'PS',
      avatarColor: '#7C3AED',
      stat: '220 sessions logged',
      isFollowing: false,
    },
    {
      id: 'll-3',
      name: 'Chen Wei',
      subtitle: 'Music · Piano',
      avatarInitials: 'CW',
      avatarColor: '#059669',
      stat: '340 sessions logged',
      isFollowing: false,
    },
    {
      id: 'll-4',
      name: 'Emma Larsson',
      subtitle: 'Photography · Film',
      avatarInitials: 'EL',
      avatarColor: '#D97706',
      stat: '150 sessions logged',
      isFollowing: false,
    },
    {
      id: 'll-5',
      name: 'Kwame Asante',
      subtitle: 'Chess · Strategy Games',
      avatarInitials: 'KA',
      avatarColor: '#DC2626',
      stat: '420 sessions logged',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-ll-1',
      name: 'Book Club',
      description: 'Monthly reads, discussion threads, and reading lists across genres.',
      memberCount: 4200,
      icon: 'book-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 1200,
    },
    {
      id: 'comm-ll-2',
      name: 'Language Exchange',
      description: 'Find practice partners, share resources, and discuss language learning methods.',
      memberCount: 3600,
      icon: 'chatbubbles-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 890,
    },
    {
      id: 'comm-ll-3',
      name: 'Learning Methods',
      description: 'Spaced repetition, deliberate practice, and evidence-based study techniques.',
      memberCount: 2800,
      icon: 'bulb-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 540,
    },
  ],
  posts: [
    {
      id: 'post-ll-1',
      communityName: 'Learning Methods',
      authorName: 'Priya Sharma',
      authorInitials: 'PS',
      authorColor: '#7C3AED',
      title: 'How I use interleaving to learn 3 subjects simultaneously without confusion',
      body: 'Instead of blocking my study time by subject, I rotate between philosophy, creative writing, and history in 25-minute Pomodoros. Counterintuitively, the context switching actually helps retention because I\'m constantly re-activating each subject.',
      postType: 'tip',
      topicTags: [
        { label: 'Study Methods', color: '#7C3AED' },
        { label: 'Interleaving', color: '#2563EB' },
      ],
      upvotes: 94,
      commentCount: 27,
      viewCount: 1800,
      timeAgo: '4h ago',
    },
    {
      id: 'post-ll-2',
      communityName: 'Language Exchange',
      authorName: 'Marcus Rivera',
      authorInitials: 'MR',
      authorColor: '#2563EB',
      title: 'Hit B2 in Japanese after 18 months — what actually worked',
      body: 'Passed JLPT N3 and my tutor says I\'m solidly B2 conversational. The secret: I stopped studying grammar textbooks and started reading manga with a dictionary. Comprehensible input > drilling exercises.',
      postType: 'discussion',
      topicTags: [
        { label: 'Japanese', color: '#DC2626' },
        { label: 'Progress Report', color: '#059669' },
      ],
      upvotes: 142,
      commentCount: 38,
      viewCount: 3200,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Regenerative Agriculture
// ---------------------------------------------------------------------------

const REGEN_AG_DATA: InterestConnectData = {
  peersHeader: 'Growers to Follow',
  searchPlaceholder: 'Search growers',
  peers: [
    {
      id: 'regen-1',
      name: 'Miguel Torres',
      subtitle: 'Soil Health · Cover Cropping',
      avatarInitials: 'MT',
      avatarColor: '#059669',
      stat: '6 growing seasons',
      isFollowing: false,
    },
    {
      id: 'regen-2',
      name: 'Sarah Greenfield',
      subtitle: 'Permaculture · Food Forests',
      avatarInitials: 'SG',
      avatarColor: '#2563EB',
      stat: '8 growing seasons',
      isFollowing: false,
    },
    {
      id: 'regen-3',
      name: 'Raj Patel',
      subtitle: 'Composting · Soil Biology',
      avatarInitials: 'RP',
      avatarColor: '#D97706',
      stat: '4 growing seasons',
      isFollowing: false,
    },
    {
      id: 'regen-4',
      name: 'Kimi Nakamura',
      subtitle: 'No-Till · Market Garden',
      avatarInitials: 'KN',
      avatarColor: '#DC2626',
      stat: '10 growing seasons',
      isFollowing: false,
    },
    {
      id: 'regen-5',
      name: 'Blessing Moyo',
      subtitle: 'Agroforestry · Water Systems',
      avatarInitials: 'BM',
      avatarColor: '#7C3AED',
      stat: '5 growing seasons',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-regen-1',
      name: 'Soil Health Network',
      description: 'Soil testing, biology, amendments, and building living soil systems.',
      memberCount: 2400,
      icon: 'leaf-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 560,
    },
    {
      id: 'comm-regen-2',
      name: 'Cover Crop Exchange',
      description: 'Species selection, mixes, termination timing, and regional experiences.',
      memberCount: 1800,
      icon: 'flower-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 380,
    },
    {
      id: 'comm-regen-3',
      name: 'Market Garden',
      description: 'No-till beds, succession planting, and direct-to-consumer sales strategies.',
      memberCount: 3200,
      icon: 'storefront-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 740,
    },
  ],
  posts: [
    {
      id: 'post-regen-1',
      communityName: 'Soil Health Network',
      authorName: 'Miguel Torres',
      authorInitials: 'MT',
      authorColor: '#059669',
      title: 'Year 3 soil test results after switching to no-till: organic matter up 1.2%',
      body: 'Started at 2.8% OM, now at 4.0% after 3 years of no-till, cover cropping, and compost applications. The biggest change was in water infiltration — went from 45 minutes per inch to 12 minutes. The soil is alive.',
      postType: 'discussion',
      topicTags: [
        { label: 'Soil Health', color: '#059669' },
        { label: 'No-Till', color: '#D97706' },
      ],
      upvotes: 108,
      commentCount: 29,
      viewCount: 1600,
      timeAgo: '5h ago',
    },
    {
      id: 'post-regen-2',
      communityName: 'Cover Crop Exchange',
      authorName: 'Sarah Greenfield',
      authorInitials: 'SG',
      authorColor: '#2563EB',
      title: 'My go-to 5-species cover crop mix for zone 6b',
      body: 'After testing dozens of combos: crimson clover, cereal rye, daikon radish, field peas, and oats. Plant by Sept 15 in my area. The daikon breaks up compaction, the rye provides biomass, and the legumes fix nitrogen. Total seed cost about $45/acre.',
      postType: 'tip',
      topicTags: [
        { label: 'Cover Crops', color: '#2563EB' },
        { label: 'Seed Mix', color: '#059669' },
      ],
      upvotes: 87,
      commentCount: 22,
      viewCount: 1200,
      timeAgo: '1d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Design
// ---------------------------------------------------------------------------

const DESIGN_DATA: InterestConnectData = {
  peersHeader: 'Designers to Follow',
  searchPlaceholder: 'Search designers',
  peers: [
    {
      id: 'designer-1',
      name: 'Aiko Tanaka',
      subtitle: 'UX Design · Design Systems',
      avatarInitials: 'AT',
      avatarColor: '#6366F1',
      stat: '78 projects shared',
      isFollowing: false,
    },
    {
      id: 'designer-2',
      name: 'Marcus Reid',
      subtitle: 'Brand Identity · Typography',
      avatarInitials: 'MR',
      avatarColor: '#DC2626',
      stat: '52 projects shared',
      isFollowing: false,
    },
    {
      id: 'designer-3',
      name: 'Priya Sharma',
      subtitle: 'Product Design · Prototyping',
      avatarInitials: 'PS',
      avatarColor: '#059669',
      stat: '95 projects shared',
      isFollowing: false,
    },
    {
      id: 'designer-4',
      name: 'Leo Andersson',
      subtitle: 'Motion Design · 3D',
      avatarInitials: 'LA',
      avatarColor: '#D97706',
      stat: '41 projects shared',
      isFollowing: false,
    },
    {
      id: 'designer-5',
      name: 'Camille Dubois',
      subtitle: 'Graphic Design · Editorial',
      avatarInitials: 'CD',
      avatarColor: '#7C3AED',
      stat: '63 projects shared',
      isFollowing: false,
    },
    {
      id: 'designer-6',
      name: 'Jin Park',
      subtitle: 'Interaction Design · Accessibility',
      avatarInitials: 'JP',
      avatarColor: '#0891B2',
      stat: '110 projects shared',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-design-1',
      name: 'Design Systems',
      description: 'Tokens, components, documentation, and scaling design across teams.',
      memberCount: 3400,
      icon: 'grid-outline',
      iconColor: '#6366F1',
      iconBgColor: '#EEF2FF',
      postCount: 560,
    },
    {
      id: 'comm-design-2',
      name: 'Typography & Layout',
      description: 'Type pairings, grid systems, and the craft of beautiful text.',
      memberCount: 2100,
      icon: 'text-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 340,
    },
    {
      id: 'comm-design-3',
      name: 'Portfolio & Career',
      description: 'Portfolio reviews, job search tips, and career growth discussions.',
      memberCount: 4800,
      icon: 'briefcase-outline',
      iconColor: '#059669',
      iconBgColor: '#D1FAE5',
      postCount: 920,
    },
    {
      id: 'comm-design-4',
      name: 'Tools & Workflow',
      description: 'Figma, Framer, Sketch, and the tools that power your process.',
      memberCount: 5600,
      icon: 'construct-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 1100,
    },
    {
      id: 'comm-design-5',
      name: 'Design Critique',
      description: 'Share work-in-progress and get constructive feedback from peers.',
      memberCount: 1900,
      icon: 'chatbubble-ellipses-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 280,
    },
  ],
  posts: [
    {
      id: 'post-design-1',
      communityName: 'Design Systems',
      authorName: 'Aiko Tanaka',
      authorInitials: 'AT',
      authorColor: '#6366F1',
      title: 'How we migrated 200+ components to design tokens without breaking production',
      body: 'Our team spent 3 months migrating from hardcoded values to a token-based system. The key was building a codemods pipeline and doing it in layers — color first, then spacing, then typography.',
      postType: 'discussion' as const,
      topicTags: [
        { label: 'Design Tokens', color: '#6366F1' },
        { label: 'Migration', color: '#059669' },
      ],
      upvotes: 156,
      commentCount: 42,
      viewCount: 3200,
      timeAgo: '6h ago',
      comments: [
        { id: 'c-d1-1', authorName: 'Jin Park', authorInitials: 'JP', authorColor: '#0891B2', body: 'Did you handle dark mode tokens at the same time or was that a separate pass?', timeAgo: '5h ago', upvotes: 12 },
        { id: 'c-d1-2', authorName: 'Aiko Tanaka', authorInitials: 'AT', authorColor: '#6366F1', body: 'Separate pass — we added semantic aliases (surface-primary, text-primary) that mapped to different values per theme. Much cleaner than conditional logic.', timeAgo: '4h ago', upvotes: 24 },
      ],
    },
    {
      id: 'post-design-2',
      communityName: 'Typography & Layout',
      authorName: 'Marcus Reid',
      authorInitials: 'MR',
      authorColor: '#DC2626',
      title: 'The 4px baseline grid changed everything about my layouts',
      body: 'Switched from arbitrary spacing to a strict 4px grid 6 months ago. Every element snaps, vertical rhythm is automatic, and handoff to engineering is way smoother.',
      postType: 'tip' as const,
      topicTags: [
        { label: 'Layout', color: '#DC2626' },
        { label: 'Spacing', color: '#6366F1' },
      ],
      upvotes: 98,
      commentCount: 18,
      viewCount: 2100,
      timeAgo: '1d ago',
    },
    {
      id: 'post-design-3',
      communityName: 'Tools & Workflow',
      authorName: 'Priya Sharma',
      authorInitials: 'PS',
      authorColor: '#059669',
      title: 'Figma variables vs. styles — when to use which?',
      body: 'Now that Figma has variables, I keep going back and forth on when to use variables vs. traditional styles. Anyone have a clear mental model?',
      postType: 'question' as const,
      topicTags: [
        { label: 'Figma', color: '#D97706' },
        { label: 'Workflow', color: '#059669' },
      ],
      upvotes: 67,
      commentCount: 35,
      viewCount: 1800,
      timeAgo: '1d ago',
    },
    {
      id: 'post-design-4',
      communityName: 'Design Critique',
      authorName: 'Camille Dubois',
      authorInitials: 'CD',
      authorColor: '#7C3AED',
      title: 'Feedback on my magazine redesign concept — going for brutalist meets editorial',
      body: 'Experimenting with heavy type, monochrome palette, and asymmetric grids for an independent music magazine. Looking for honest critique on readability vs. impact.',
      postType: 'discussion' as const,
      topicTags: [
        { label: 'Editorial', color: '#7C3AED' },
        { label: 'Critique', color: '#DC2626' },
      ],
      upvotes: 43,
      commentCount: 21,
      viewCount: 980,
      timeAgo: '2d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Golf
// ---------------------------------------------------------------------------

const GOLF_DATA: InterestConnectData = {
  peersHeader: 'Golfers to Follow',
  searchPlaceholder: 'Search golfers',
  peers: [
    {
      id: 'golfer-1',
      name: 'Tom Mitchell',
      subtitle: 'Single Digit · Course Strategy',
      avatarInitials: 'TM',
      avatarColor: '#166534',
      stat: '340 rounds logged',
      isFollowing: false,
    },
    {
      id: 'golfer-2',
      name: 'Sarah Johansson',
      subtitle: 'Mid-Handicap · Short Game',
      avatarInitials: 'SJ',
      avatarColor: '#2563EB',
      stat: '185 rounds logged',
      isFollowing: false,
    },
    {
      id: 'golfer-3',
      name: 'David Park',
      subtitle: 'Scratch Golfer · Competitive',
      avatarInitials: 'DP',
      avatarColor: '#DC2626',
      stat: '520 rounds logged',
      isFollowing: false,
    },
    {
      id: 'golfer-4',
      name: 'Rachel Torres',
      subtitle: 'Beginner · Learning Journey',
      avatarInitials: 'RT',
      avatarColor: '#D97706',
      stat: '62 rounds logged',
      isFollowing: false,
    },
    {
      id: 'golfer-5',
      name: 'James O\'Brien',
      subtitle: 'Club Fitting · Equipment',
      avatarInitials: 'JO',
      avatarColor: '#374151',
      stat: '290 rounds logged',
      isFollowing: false,
    },
    {
      id: 'golfer-6',
      name: 'Linda Chen',
      subtitle: 'Teaching Pro · Swing Analysis',
      avatarInitials: 'LC',
      avatarColor: '#7C3AED',
      stat: '48 lessons shared',
      isFollowing: false,
    },
  ],
  communities: [
    {
      id: 'comm-golf-1',
      name: 'Swing Tips',
      description: 'Swing mechanics, drills, and video analysis from players and coaches.',
      memberCount: 5200,
      icon: 'golf-outline',
      iconColor: '#166534',
      iconBgColor: '#DCFCE7',
      postCount: 1200,
    },
    {
      id: 'comm-golf-2',
      name: 'Course Reviews',
      description: 'Play reports, hidden gems, and honest reviews of courses worldwide.',
      memberCount: 3800,
      icon: 'map-outline',
      iconColor: '#2563EB',
      iconBgColor: '#DBEAFE',
      postCount: 680,
    },
    {
      id: 'comm-golf-3',
      name: 'Equipment & Gear',
      description: 'Club reviews, fitting experiences, ball comparisons, and deals.',
      memberCount: 6100,
      icon: 'construct-outline',
      iconColor: '#D97706',
      iconBgColor: '#FEF3C7',
      postCount: 1450,
    },
    {
      id: 'comm-golf-4',
      name: 'Short Game Lab',
      description: 'Chipping, pitching, bunker play, and putting — the scoring zone.',
      memberCount: 2900,
      icon: 'flag-outline',
      iconColor: '#DC2626',
      iconBgColor: '#FEE2E2',
      postCount: 520,
    },
    {
      id: 'comm-golf-5',
      name: 'Mental Game',
      description: 'Pre-shot routines, course management, and staying composed under pressure.',
      memberCount: 1800,
      icon: 'bulb-outline',
      iconColor: '#7C3AED',
      iconBgColor: '#EDE9FE',
      postCount: 310,
    },
  ],
  posts: [
    {
      id: 'post-golf-1',
      communityName: 'Swing Tips',
      authorName: 'David Park',
      authorInitials: 'DP',
      authorColor: '#DC2626',
      title: 'The one drill that fixed my early extension for good',
      body: 'Struggled with early extension for years — tried everything. What finally clicked was the "wall drill" where you set up with your glutes touching a wall. 3 weeks of daily reps and my swing path is totally different.',
      postType: 'tip' as const,
      topicTags: [
        { label: 'Swing', color: '#166534' },
        { label: 'Drill', color: '#D97706' },
      ],
      upvotes: 142,
      commentCount: 38,
      viewCount: 3100,
      timeAgo: '5h ago',
      comments: [
        { id: 'c-g1-1', authorName: 'Linda Chen', authorInitials: 'LC', authorColor: '#7C3AED', body: 'Great drill! I use this with all my students. Pro tip: film yourself from down the line to verify your pelvis stays back through impact.', timeAgo: '4h ago', upvotes: 22 },
        { id: 'c-g1-2', authorName: 'Tom Mitchell', authorInitials: 'TM', authorColor: '#166534', body: 'Tried this today at the range. Feels weird but my contact was so much more solid. Thanks for sharing.', timeAgo: '2h ago', upvotes: 8 },
      ],
    },
    {
      id: 'post-golf-2',
      communityName: 'Equipment & Gear',
      authorName: 'James O\'Brien',
      authorInitials: 'JO',
      authorColor: '#374151',
      title: 'Got fitted for irons — the numbers blew my mind',
      body: 'Playing off-the-rack irons for 10 years. Finally got a proper fitting — 2 degrees upright, half inch long, and stiffer shafts. Gained 15 yards and my dispersion tightened by 30%.',
      postType: 'discussion' as const,
      topicTags: [
        { label: 'Club Fitting', color: '#374151' },
        { label: 'Irons', color: '#2563EB' },
      ],
      upvotes: 89,
      commentCount: 27,
      viewCount: 2400,
      timeAgo: '1d ago',
    },
    {
      id: 'post-golf-3',
      communityName: 'Short Game Lab',
      authorName: 'Sarah Johansson',
      authorInitials: 'SJ',
      authorColor: '#2563EB',
      title: 'How do you practice bunker shots when your range doesn\'t have a bunker?',
      body: 'My local range has zero bunker practice areas. I dread bunker shots on the course because I never get to practice. Any creative solutions?',
      postType: 'question' as const,
      topicTags: [
        { label: 'Bunker', color: '#DC2626' },
        { label: 'Practice', color: '#166534' },
      ],
      upvotes: 34,
      commentCount: 19,
      viewCount: 890,
      timeAgo: '1d ago',
    },
    {
      id: 'post-golf-4',
      communityName: 'Mental Game',
      authorName: 'Tom Mitchell',
      authorInitials: 'TM',
      authorColor: '#166534',
      title: 'Stopped keeping score for a month — here\'s what happened',
      body: 'After a bad stretch I decided to play 4 rounds without keeping score, just focusing on process goals. When I went back to scoring, I shot my best round of the year.',
      postType: 'discussion' as const,
      topicTags: [
        { label: 'Mental Game', color: '#7C3AED' },
        { label: 'Mindset', color: '#166534' },
      ],
      upvotes: 178,
      commentCount: 45,
      viewCount: 4100,
      timeAgo: '2d ago',
    },
  ],
};

// ---------------------------------------------------------------------------
// Lookup
// ---------------------------------------------------------------------------

const CONNECT_DATA_BY_INTEREST: Record<string, InterestConnectData> = {
  nursing: NURSING_DATA,
  drawing: DRAWING_DATA,
  design: DESIGN_DATA,
  fitness: FITNESS_DATA,
  'health-and-fitness': FITNESS_DATA,
  golf: GOLF_DATA,
  knitting: KNITTING_DATA,
  'fiber-arts': FIBER_ARTS_DATA,
  'global-health': GLOBAL_HEALTH_DATA,
  'painting-printing': PAINTING_DATA,
  'lifelong-learning': LIFELONG_LEARNING_DATA,
  'regenerative-agriculture': REGEN_AG_DATA,
};

/**
 * Get demo Connect tab data for a given interest slug.
 * Returns null for sail-racing (which uses live data).
 */
export function getConnectDemoData(interestSlug: string): InterestConnectData | null {
  return CONNECT_DATA_BY_INTEREST[interestSlug] ?? null;
}
