-- Expand boat classes with comprehensive selection
-- Adds more keelboats, dinghies, multihulls, regional classes, and cruiser/racers

INSERT INTO boat_classes (name, class_association, metadata) VALUES

-- === Additional J/Boats ===
('J/88', 'J/88 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":8.84}'::jsonb),
('J/99', 'J/99 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.91}'::jsonb),
('J/111', 'J/111 Class Association', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":11.10}'::jsonb),
('J/112E', 'J/Boats', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.28}'::jsonb),
('J/121', 'J/121 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":12.04}'::jsonb),
('J/122', 'J/122 Class Association', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":12.19}'::jsonb),
('J/35', 'J/35 Class Association', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":10.67}'::jsonb),
('J/44', 'J/44 Class Association', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":13.41}'::jsonb),
('J/30', 'J/30 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.14}'::jsonb),
('J/29', 'J/29 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.84}'::jsonb),
('J/92s', 'J/92s Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.14}'::jsonb),
('J/120', 'J/120 Class Association', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.04}'::jsonb),
('J/125', 'J/125 Class Association', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":12.50}'::jsonb),
('J/145', 'J/Boats', '{"type":"keelboat","crew":10,"one_design":true,"loa_m":14.48}'::jsonb),
('J/160', 'J/Boats', '{"type":"keelboat","crew":10,"one_design":true,"loa_m":16.00}'::jsonb),

-- === Beneteau First Series ===
('Beneteau First 14', 'Beneteau', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.25}'::jsonb),
('Beneteau First 18', 'Beneteau', '{"type":"keelboat","crew":3,"one_design":true,"loa_m":5.40}'::jsonb),
('Beneteau First 20', 'Beneteau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":6.17}'::jsonb),
('Beneteau First 24', 'Beneteau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.49}'::jsonb),
('Beneteau First 27.7', 'Beneteau', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.49}'::jsonb),
('Beneteau First 31.7', 'Beneteau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":9.61}'::jsonb),
('Beneteau First 34.7', 'Beneteau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.50}'::jsonb),
('Beneteau First 40', 'Beneteau', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":12.24}'::jsonb),
('Beneteau First 40.7', 'Beneteau', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":12.34}'::jsonb),
('Beneteau Figaro 3', 'Beneteau', '{"type":"keelboat","crew":2,"one_design":true,"foiling":true,"loa_m":9.76}'::jsonb),

-- === Catalina ===
('Catalina 22', 'Catalina 22 National Sailing Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":6.71}'::jsonb),
('Catalina 25', 'Catalina 25 Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.62}'::jsonb),
('Catalina 27', 'Catalina 27 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.23}'::jsonb),
('Catalina 30', 'Catalina 30 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.14}'::jsonb),
('Catalina 34', 'Catalina 34 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.36}'::jsonb),
('Catalina 36', 'Catalina 36 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.97}'::jsonb),
('Catalina 38', 'Catalina Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.58}'::jsonb),
('Catalina 42', 'Catalina Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.70}'::jsonb),
('Catalina 275 Sport', 'Catalina Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":8.38}'::jsonb),
('Catalina 315', 'Catalina Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.53}'::jsonb),

-- === Hunter ===
('Hunter 170', 'Hunter Marine', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":5.18}'::jsonb),
('Hunter 22', 'Hunter Marine', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":6.70}'::jsonb),
('Hunter 25', 'Hunter Marine', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.62}'::jsonb),
('Hunter 27', 'Hunter Marine', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.23}'::jsonb),
('Hunter 31', 'Hunter Marine', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.45}'::jsonb),
('Hunter 33', 'Hunter Marine', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.06}'::jsonb),
('Hunter 36', 'Hunter Marine', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.97}'::jsonb),
('Hunter 40', 'Hunter Marine', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.19}'::jsonb),

-- === C&C ===
('C&C 24', 'C&C Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.32}'::jsonb),
('C&C 27', 'C&C Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.23}'::jsonb),
('C&C 29', 'C&C Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.84}'::jsonb),
('C&C 30', 'C&C Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.14}'::jsonb),
('C&C 33', 'C&C Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.06}'::jsonb),
('C&C 34', 'C&C Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.36}'::jsonb),
('C&C 35', 'C&C Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.67}'::jsonb),
('C&C 37', 'C&C Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":11.28}'::jsonb),
('C&C 40', 'C&C Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.19}'::jsonb),
('C&C 44', 'C&C Yachts', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":13.41}'::jsonb),

-- === More Melges ===
('Melges 14', 'Melges Performance Sailboats', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.27}'::jsonb),
('Melges 15', 'Melges Performance Sailboats', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.57}'::jsonb),
('Melges MC', 'Melges Performance Sailboats', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.81}'::jsonb),
('Melges 40', 'Melges 40 Class Association', '{"type":"sport_boat","crew":8,"one_design":true,"loa_m":12.19}'::jsonb),
('Melges IC37', 'Melges IC37 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.28}'::jsonb),

-- === RS Sailing ===
('RS 100', 'RS Sailing', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.85}'::jsonb),
('RS 200', 'RS Sailing', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.00}'::jsonb),
('RS 300', 'RS Sailing', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.24}'::jsonb),
('RS 400', 'RS Sailing', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.54}'::jsonb),
('RS 500', 'RS Sailing', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.54}'::jsonb),
('RS 600', 'RS Sailing', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.50}'::jsonb),
('RS 700', 'RS Sailing', '{"type":"skiff","crew":1,"one_design":true,"loa_m":4.60}'::jsonb),
('RS 800', 'RS Sailing', '{"type":"skiff","crew":2,"one_design":true,"loa_m":4.80}'::jsonb),
('RS Tera', 'RS Sailing', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.87}'::jsonb),
('RS Venture', 'RS Sailing', '{"type":"dinghy","crew":3,"one_design":true,"loa_m":4.60}'::jsonb),
('RS Vareo', 'RS Sailing', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.40}'::jsonb),
('RS Quba', 'RS Sailing', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":3.54}'::jsonb),
('RS Zest', 'RS Sailing', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":3.54}'::jsonb),
('RS Cat 14', 'RS Sailing', '{"type":"multihull","crew":2,"one_design":true,"loa_m":4.27}'::jsonb),
('RS Cat 16', 'RS Sailing', '{"type":"multihull","crew":2,"one_design":true,"loa_m":4.88}'::jsonb),

-- === Laser/ILCA Performance dinghies ===
('Laser Pico', 'Laser', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":3.56}'::jsonb),
('Laser Stratos', 'Laser', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.33}'::jsonb),
('Laser Bahia', 'Laser', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.69}'::jsonb),
('Laser Vago', 'Laser', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.20}'::jsonb),

-- === Youth/Junior classes ===
('O''pen Skiff', 'International Open Skiff Class', '{"type":"skiff","crew":1,"one_design":true,"youth":true,"loa_m":2.75}'::jsonb),
('Sabot', 'International Sabot Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.44}'::jsonb),
('Naples Sabot', 'Naples Sabot Class Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.44}'::jsonb),
('El Toro', 'El Toro International Yacht Racing Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.44}'::jsonb),
('Splash', 'Splash Class Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.70}'::jsonb),
('Byte', 'Byte Class Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":3.66}'::jsonb),
('Byte CII', 'Byte Class Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":3.66}'::jsonb),
('Club 420', 'Club 420 Class Association', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":4.20}'::jsonb),
('Flying Junior (FJ)', 'International Flying Junior Class Association', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":4.03}'::jsonb),
('C420', 'C420 Class Association', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":4.20}'::jsonb),
('CFJ', 'CFJ Class', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":4.03}'::jsonb),
('Cadet', 'International Cadet Class', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":3.22}'::jsonb),
('Bug', 'Bug Class Association', '{"type":"dinghy","crew":1,"one_design":true,"youth":true,"loa_m":2.44}'::jsonb),

-- === British/European popular classes ===
('Enterprise', 'Enterprise Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.04}'::jsonb),
('Wayfarer', 'Wayfarer International Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.82}'::jsonb),
('GP14', 'GP14 Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.27}'::jsonb),
('Solo', 'Solo Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.79}'::jsonb),
('Merlin Rocket', 'Merlin Rocket Owners Association', '{"type":"dinghy","crew":2,"one_design":false,"loa_m":4.27}'::jsonb),
('National 12', 'National 12 Owners Association', '{"type":"dinghy","crew":2,"one_design":false,"loa_m":3.66}'::jsonb),
('International 14', 'International 14 Class Association', '{"type":"skiff","crew":2,"one_design":false,"loa_m":4.27}'::jsonb),
('Albacore', 'International Albacore Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.57}'::jsonb),
('Graduate', 'Graduate Owners Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":3.81}'::jsonb),
('Lark', 'Lark Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.11}'::jsonb),
('Scorpion', 'Scorpion Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.27}'::jsonb),
('Leader', 'Leader Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.27}'::jsonb),
('Osprey', 'Osprey Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":5.33}'::jsonb),
('Phantom', 'Phantom Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.42}'::jsonb),
('Streaker', 'Streaker Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.80}'::jsonb),
('Blaze', 'Blaze Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.20}'::jsonb),
('Supernova', 'Supernova Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.19}'::jsonb),
('Contender', 'International Contender Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.88}'::jsonb),
('Buzz', 'Buzz Class Association', '{"type":"dinghy","crew":2,"one_design":true,"loa_m":4.10}'::jsonb),
('B14', 'International B14 Class Association', '{"type":"skiff","crew":2,"one_design":true,"loa_m":4.27}'::jsonb),
('Musto Skiff', 'Musto Skiff Class Association', '{"type":"skiff","crew":1,"one_design":true,"loa_m":4.55}'::jsonb),
('Norfolk Punt', 'Norfolk Punt Club', '{"type":"dinghy","crew":2,"one_design":false,"loa_m":6.71}'::jsonb),

-- === More Hobie classes ===
('Hobie 14', 'Hobie Class Association', '{"type":"multihull","crew":1,"one_design":true,"loa_m":4.27}'::jsonb),
('Hobie 17', 'Hobie Class Association', '{"type":"multihull","crew":1,"one_design":true,"loa_m":5.18}'::jsonb),
('Hobie 18', 'Hobie Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.49}'::jsonb),
('Hobie 20', 'Hobie Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":6.10}'::jsonb),
('Hobie 21', 'Hobie Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":6.40}'::jsonb),
('Hobie Getaway', 'Hobie Class Association', '{"type":"multihull","crew":4,"one_design":true,"loa_m":5.33}'::jsonb),
('Hobie Tiger', 'Hobie Class Association', '{"type":"multihull","crew":2,"one_design":true,"foiling":false,"loa_m":5.52}'::jsonb),
('Hobie Wildcat', 'Hobie Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.52}'::jsonb),

-- === More multihulls ===
('Prindle 16', 'Prindle Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":4.88}'::jsonb),
('Prindle 18', 'Prindle Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.49}'::jsonb),
('Prindle 19', 'Prindle Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.79}'::jsonb),
('Nacra 15', 'Nacra Class Association', '{"type":"multihull","crew":2,"one_design":true,"youth":true,"loa_m":4.67}'::jsonb),
('Nacra 500', 'Nacra Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.00}'::jsonb),
('Nacra 570', 'Nacra Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.70}'::jsonb),
('Nacra F18 Infusion', 'Nacra Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.52}'::jsonb),
('Nacra F20 Carbon', 'Nacra Class Association', '{"type":"multihull","crew":2,"one_design":true,"foiling":true,"loa_m":6.10}'::jsonb),
('Inter 17', 'Inter 17 Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.18}'::jsonb),
('Inter 18', 'Inter 18 Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.49}'::jsonb),
('Taipan', 'Taipan Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":4.93}'::jsonb),
('Mystere', 'Mystere Class Association', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.00}'::jsonb),
('Goodall C2', 'Goodall Design', '{"type":"multihull","crew":2,"one_design":true,"loa_m":5.49}'::jsonb),

-- === Windsurfers ===
('RSX', 'World Sailing', '{"type":"windsurf","crew":1,"one_design":true,"olympic":false}'::jsonb),
('Techno 293', 'Techno 293 Class', '{"type":"windsurf","crew":1,"one_design":true,"youth":true}'::jsonb),
('Formula Windsurfing', 'International Windsurfing Association', '{"type":"windsurf","crew":1,"one_design":false}'::jsonb),
('Raceboard', 'International Windsurfing Association', '{"type":"windsurf","crew":1,"one_design":true}'::jsonb),
('Windfoil', 'International Windsurfing Association', '{"type":"windsurf","crew":1,"foiling":true}'::jsonb),

-- === Kiteboarding ===
('Formula Kite', 'International Kiteboarding Association', '{"type":"kite","crew":1,"one_design":true,"foiling":true}'::jsonb),
('Twin Tip Racing', 'International Kiteboarding Association', '{"type":"kite","crew":1,"one_design":false}'::jsonb),

-- === Classic/Traditional classes ===
('Dragon (Classic)', 'International Dragon Association', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":8.90}'::jsonb),
('Folkboat', 'International Folkboat Class', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":7.70}'::jsonb),
('Nordic Folkboat', 'Nordic Folkboat Class', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":7.70}'::jsonb),
('IOD', 'International One Design Class', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":10.16}'::jsonb),
('Shields', 'Shields Class Association', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":9.14}'::jsonb),
('Alerion Express 28', 'Alerion Yachts', '{"type":"keelboat","crew":4,"one_design":true,"classic":true,"loa_m":8.53}'::jsonb),
('Rhodes 19', 'Rhodes 19 Class Association', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":5.79}'::jsonb),
('Ensign', 'Ensign Class Association', '{"type":"keelboat","crew":4,"one_design":true,"classic":true,"loa_m":6.71}'::jsonb),
('Highlander', 'Highlander Class Association', '{"type":"dinghy","crew":2,"one_design":true,"classic":true,"loa_m":6.10}'::jsonb),
('Lightning', 'International Lightning Class Association', '{"type":"dinghy","crew":3,"one_design":true,"classic":true,"loa_m":5.79}'::jsonb),
('Blue Jay', 'Blue Jay Class Association', '{"type":"dinghy","crew":2,"one_design":true,"classic":true,"youth":true,"loa_m":4.11}'::jsonb),
('Thistle', 'Thistle Class Association', '{"type":"dinghy","crew":3,"one_design":true,"classic":true,"loa_m":5.18}'::jsonb),
('Flying Scot', 'Flying Scot Sailing Association', '{"type":"dinghy","crew":3,"one_design":true,"classic":true,"loa_m":5.79}'::jsonb),
('Penguin', 'Penguin Class Dinghy Association', '{"type":"dinghy","crew":2,"one_design":true,"classic":true,"loa_m":3.51}'::jsonb),
('Raven', 'Raven Class Association', '{"type":"keelboat","crew":3,"one_design":true,"classic":true,"loa_m":7.32}'::jsonb),
('Comet', 'Comet Class Association', '{"type":"dinghy","crew":1,"one_design":true,"classic":true,"loa_m":3.66}'::jsonb),
('Mariner', 'Mariner Class Association', '{"type":"dinghy","crew":2,"one_design":true,"classic":true,"loa_m":4.70}'::jsonb),
('Tech Dinghy', 'Tech Dinghy Association', '{"type":"dinghy","crew":3,"one_design":true,"classic":true,"loa_m":3.94}'::jsonb),
('M Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":3,"one_design":true,"classic":true,"loa_m":4.88}'::jsonb),
('E Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":3,"one_design":true,"loa_m":8.53}'::jsonb),
('A Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":4,"one_design":true,"loa_m":11.58}'::jsonb),
('C Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":3,"one_design":true,"loa_m":6.10}'::jsonb),
('MC Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":4.88}'::jsonb),
('X Scow', 'Inland Lake Yachting Association', '{"type":"dinghy","crew":2,"one_design":true,"youth":true,"loa_m":4.88}'::jsonb),

-- === More sport boats ===
('Beneteau Platu 25', 'Platu 25 Class Association', '{"type":"sport_boat","crew":5,"one_design":true,"loa_m":7.62}'::jsonb),
('SB3', 'SB3 Class Association', '{"type":"sport_boat","crew":3,"one_design":true,"loa_m":6.19}'::jsonb),
('Seascape 18', 'Seascape', '{"type":"sport_boat","crew":2,"one_design":true,"loa_m":5.55}'::jsonb),
('Seascape 24', 'Seascape', '{"type":"sport_boat","crew":4,"one_design":true,"loa_m":7.40}'::jsonb),
('Seascape 27', 'Seascape', '{"type":"sport_boat","crew":4,"one_design":true,"loa_m":8.20}'::jsonb),
('Open 5.70', 'Open 5.70 Class Association', '{"type":"sport_boat","crew":2,"one_design":true,"loa_m":5.70}'::jsonb),
('L30', 'L30 Class Association', '{"type":"sport_boat","crew":6,"one_design":true,"loa_m":9.40}'::jsonb),
('Soto 40', 'Soto 40 Class Association', '{"type":"sport_boat","crew":8,"one_design":true,"loa_m":12.19}'::jsonb),
('Open 6.5 (Mini Proto)', 'Classe Mini', '{"type":"sport_boat","crew":1,"one_design":false,"loa_m":6.50}'::jsonb),
('Cape 31', 'Cape 31 Class Association', '{"type":"sport_boat","crew":7,"one_design":true,"loa_m":9.45}'::jsonb),
('Corinthian', 'Corinthian Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":8.08}'::jsonb),

-- === Performance cruisers / Racer-Cruisers ===
('Jeanneau Sun Fast 3200', 'Jeanneau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.76}'::jsonb),
('Jeanneau Sun Fast 3300', 'Jeanneau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.91}'::jsonb),
('Jeanneau Sun Fast 3600', 'Jeanneau', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.97}'::jsonb),
('Dehler 30 OD', 'Dehler', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.40}'::jsonb),
('Dehler 34', 'Dehler', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.36}'::jsonb),
('Dehler 38', 'Dehler', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.58}'::jsonb),
('Elan 310', 'Elan Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.45}'::jsonb),
('Elan 340', 'Elan Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.36}'::jsonb),
('Elan 350', 'Elan Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.67}'::jsonb),
('X-35', 'X-Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.67}'::jsonb),
('X-41', 'X-Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.50}'::jsonb),
('X-55', 'X-Yachts', '{"type":"keelboat","crew":10,"one_design":true,"loa_m":16.76}'::jsonb),
('X-46', 'X-Yachts', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":14.02}'::jsonb),
('Xp 44', 'X-Yachts', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":13.41}'::jsonb),
('Xp 50', 'X-Yachts', '{"type":"keelboat","crew":10,"one_design":true,"loa_m":15.24}'::jsonb),
('Arcona 340', 'Arcona Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.36}'::jsonb),
('Arcona 380', 'Arcona Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.58}'::jsonb),
('Salona 35', 'AD Boats', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.67}'::jsonb),
('Salona 380', 'AD Boats', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.58}'::jsonb),
('Italia 9.98', 'Italia Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":9.98}'::jsonb),
('Italia 11.98', 'Italia Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":11.98}'::jsonb),
('Grand Soleil 34', 'Cantiere del Pardo', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.36}'::jsonb),
('Grand Soleil 37', 'Cantiere del Pardo', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.28}'::jsonb),
('Grand Soleil 40', 'Cantiere del Pardo', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.19}'::jsonb),
('Grand Soleil 43', 'Cantiere del Pardo', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":13.10}'::jsonb),
('Swan 36', 'Nautor Swan', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.97}'::jsonb),
('Swan 42', 'Nautor Swan', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.80}'::jsonb),
('Swan 45', 'Nautor Swan', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":13.72}'::jsonb),
('Swan 50', 'Nautor Swan', '{"type":"keelboat","crew":10,"one_design":true,"loa_m":15.24}'::jsonb),
('ClubSwan 36', 'Nautor Swan', '{"type":"sport_boat","crew":6,"one_design":true,"loa_m":10.97}'::jsonb),
('ClubSwan 50', 'Nautor Swan', '{"type":"sport_boat","crew":10,"one_design":true,"loa_m":15.24}'::jsonb),

-- === Offshore ===
('Figaro 2', 'Figaro Class', '{"type":"keelboat","crew":2,"one_design":true,"loa_m":10.10}'::jsonb),
('Open 40', 'Open 40 Class', '{"type":"keelboat","crew":2,"one_design":false,"loa_m":12.19}'::jsonb),
('Open 50', 'Open 50 Class', '{"type":"keelboat","crew":2,"one_design":false,"loa_m":15.24}'::jsonb),
('Open 60', 'IMOCA', '{"type":"keelboat","crew":1,"one_design":false,"loa_m":18.28}'::jsonb),
('Multi 50', 'Multi 50 Class', '{"type":"multihull","crew":2,"one_design":false,"loa_m":15.24}'::jsonb),
('Ultime', 'Ultime Class', '{"type":"multihull","crew":6,"one_design":false,"loa_m":30.48}'::jsonb),
('MOD70', 'MOD70 Class', '{"type":"multihull","crew":6,"one_design":true,"loa_m":21.20}'::jsonb),
('Maxi 72', 'Maxi 72 Class', '{"type":"keelboat","crew":18,"one_design":true,"loa_m":21.95}'::jsonb),
('Mini Maxi', 'Mini Maxi Class', '{"type":"keelboat","crew":12,"one_design":false,"loa_m":18.29}'::jsonb),
('Maxi Racer', 'Offshore Racing Congress', '{"type":"keelboat","crew":18,"one_design":false,"loa_m":30.00}'::jsonb),

-- === Match Racing ===
('M32', 'M32 Class', '{"type":"multihull","crew":5,"one_design":true,"loa_m":9.75}'::jsonb),
('Match 40', 'World Match Racing Tour', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.19}'::jsonb),
('RSK8', 'RSK8 Class', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":8.00}'::jsonb),

-- === Foiling ===
('Phantom FOIL', 'Phantom Class', '{"type":"dinghy","crew":1,"one_design":true,"foiling":true,"loa_m":4.42}'::jsonb),
('Skeeta', 'Skeeta Class', '{"type":"dinghy","crew":1,"one_design":true,"foiling":true,"loa_m":4.00}'::jsonb),
('UFO', 'UFO Foiling', '{"type":"dinghy","crew":2,"one_design":true,"foiling":true,"loa_m":5.49}'::jsonb),
('Nikki', 'Nikki Class', '{"type":"dinghy","crew":1,"one_design":true,"foiling":true,"loa_m":4.30}'::jsonb),
('TF10', 'Foiling World', '{"type":"multihull","crew":4,"one_design":true,"foiling":true,"loa_m":10.00}'::jsonb),
('Flying Phantom', 'Flying Phantom Class', '{"type":"multihull","crew":2,"one_design":true,"foiling":true,"loa_m":5.52}'::jsonb),
('GC32', 'GC32 Class Association', '{"type":"multihull","crew":5,"one_design":true,"foiling":true,"loa_m":9.75}'::jsonb),
('Persico 69F', '69F Class', '{"type":"multihull","crew":4,"one_design":true,"foiling":true,"loa_m":6.90}'::jsonb),
('DNA F1', 'DNA Class', '{"type":"multihull","crew":1,"one_design":true,"foiling":true,"loa_m":5.00}'::jsonb),
('DNA F4', 'DNA Class', '{"type":"multihull","crew":2,"one_design":true,"foiling":true,"loa_m":5.49}'::jsonb),

-- === Regional/Country-specific ===
('Flying Fifteen', 'International Flying Fifteen Class', '{"type":"keelboat","crew":2,"one_design":true,"loa_m":6.10}'::jsonb),
('Linjett 33', 'Linjett Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.06}'::jsonb),
('H-Boat', 'International H-Boat Class', '{"type":"keelboat","crew":3,"one_design":true,"loa_m":8.28}'::jsonb),
('Yngling', 'International Yngling Association', '{"type":"keelboat","crew":3,"one_design":true,"loa_m":6.35}'::jsonb),
('2.4 Metre', 'International 2.4 Metre Class Association', '{"type":"keelboat","crew":1,"one_design":true,"loa_m":4.18}'::jsonb),
('Access 303', 'Access Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.03}'::jsonb),
('Access Liberty', 'Access Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.54}'::jsonb),
('Hansa 303', 'Hansa Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.03}'::jsonb),
('Hansa Liberty', 'Hansa Class Association', '{"type":"dinghy","crew":1,"one_design":true,"loa_m":3.54}'::jsonb),
('Squib', 'Squib Class Association', '{"type":"keelboat","crew":2,"one_design":true,"loa_m":5.79}'::jsonb),
('Sonata', 'Sonata Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":6.82}'::jsonb),
('Impala', 'Impala Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":8.53}'::jsonb),
('SB20 Sportsboat', 'SB20 Class', '{"type":"sport_boat","crew":3,"one_design":true,"loa_m":6.15}'::jsonb),
('Sigma 33', 'Sigma 33 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.06}'::jsonb),
('Quarter Tonner', 'Quarter Ton Class Association', '{"type":"keelboat","crew":4,"one_design":false,"loa_m":7.62}'::jsonb),
('Half Tonner', 'Half Ton Class Association', '{"type":"keelboat","crew":5,"one_design":false,"loa_m":9.14}'::jsonb),
('One Tonner', 'One Ton Cup', '{"type":"keelboat","crew":7,"one_design":false,"loa_m":10.36}'::jsonb),
('Three Quarter Ton', 'Three Quarter Ton Class', '{"type":"keelboat","crew":6,"one_design":false,"loa_m":9.75}'::jsonb),
('Two Tonner', 'Two Ton Class', '{"type":"keelboat","crew":9,"one_design":false,"loa_m":12.50}'::jsonb),

-- === Additional popular keelboats ===
('Cal 20', 'Cal 20 Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":6.10}'::jsonb),
('Cal 25', 'Cal 25 Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.62}'::jsonb),
('Cal 40', 'Cal 40 Class Association', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":12.19}'::jsonb),
('Olson 25', 'Olson 25 Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.62}'::jsonb),
('Olson 30', 'Olson 30 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.14}'::jsonb),
('Pearson 26', 'Pearson Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.92}'::jsonb),
('Pearson 30', 'Pearson Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.14}'::jsonb),
('Ranger 23', 'Ranger Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.01}'::jsonb),
('Santana 20', 'Santana 20 Class Association', '{"type":"keelboat","crew":3,"one_design":true,"loa_m":6.10}'::jsonb),
('Santana 25', 'Santana 25 Class Association', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.62}'::jsonb),
('Santana 35', 'Santana 35 Class Association', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.67}'::jsonb),
('Columbia 26', 'Columbia 26 Class', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":7.92}'::jsonb),
('Islander 36', 'Islander Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.97}'::jsonb),
('Martin 242', 'Martin 242 Class Association', '{"type":"sport_boat","crew":4,"one_design":true,"loa_m":7.39}'::jsonb),
('Express 27', 'Express 27 Class Association', '{"type":"sport_boat","crew":4,"one_design":true,"loa_m":8.23}'::jsonb),
('Express 34', 'Express 34 Class Association', '{"type":"sport_boat","crew":5,"one_design":true,"loa_m":10.36}'::jsonb),
('Express 37', 'Express 37 Class Association', '{"type":"sport_boat","crew":6,"one_design":true,"loa_m":11.28}'::jsonb),
('Moore 24', 'Moore 24 Class Association', '{"type":"sport_boat","crew":4,"one_design":true,"loa_m":7.32}'::jsonb),
('Wylie Wabbit', 'Wabbit Class Association', '{"type":"sport_boat","crew":3,"one_design":true,"loa_m":7.32}'::jsonb),
('Ultimate 20', 'Ultimate 20 Class Association', '{"type":"sport_boat","crew":2,"one_design":true,"loa_m":6.10}'::jsonb),
('Evelyn 32', 'Evelyn 32 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":9.75}'::jsonb),
('Tartan 10', 'Tartan 10 Class Association', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.06}'::jsonb),
('Mumm 30', 'Mumm 30 Class Association', '{"type":"sport_boat","crew":6,"one_design":true,"loa_m":9.14}'::jsonb),
('Sydney 32', 'Sydney 32 Class Association', '{"type":"sport_boat","crew":6,"one_design":true,"loa_m":9.75}'::jsonb),
('Sydney 36', 'Sydney 36 Class Association', '{"type":"sport_boat","crew":7,"one_design":true,"loa_m":10.97}'::jsonb),
('Sydney 38', 'Sydney 38 Class Association', '{"type":"sport_boat","crew":7,"one_design":true,"loa_m":11.58}'::jsonb),
('Sydney 43', 'Sydney 43 Class Association', '{"type":"sport_boat","crew":9,"one_design":true,"loa_m":13.10}'::jsonb),

-- === Cruising One-Design ===
('Beneteau Oceanis 30.1', 'Beneteau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.53}'::jsonb),
('Beneteau Oceanis 34.1', 'Beneteau', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.55}'::jsonb),
('Beneteau Oceanis 38.1', 'Beneteau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.50}'::jsonb),
('Beneteau Oceanis 40.1', 'Beneteau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":12.87}'::jsonb),
('Beneteau Oceanis 46.1', 'Beneteau', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":14.38}'::jsonb),
('Jeanneau Sun Odyssey 319', 'Jeanneau', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.67}'::jsonb),
('Jeanneau Sun Odyssey 349', 'Jeanneau', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.34}'::jsonb),
('Jeanneau Sun Odyssey 389', 'Jeanneau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.75}'::jsonb),
('Jeanneau Sun Odyssey 410', 'Jeanneau', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":12.35}'::jsonb),
('Jeanneau Sun Odyssey 440', 'Jeanneau', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":13.39}'::jsonb),
('Dufour 310', 'Dufour Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.45}'::jsonb),
('Dufour 350', 'Dufour Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.28}'::jsonb),
('Dufour 360', 'Dufour Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":10.93}'::jsonb),
('Dufour 390', 'Dufour Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.94}'::jsonb),
('Dufour 430', 'Dufour Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":13.24}'::jsonb),
('Hanse 315', 'Hanse Yachts', '{"type":"keelboat","crew":4,"one_design":true,"loa_m":9.43}'::jsonb),
('Hanse 348', 'Hanse Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.36}'::jsonb),
('Hanse 388', 'Hanse Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.38}'::jsonb),
('Hanse 418', 'Hanse Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.40}'::jsonb),
('Hanse 458', 'Hanse Yachts', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":14.10}'::jsonb),
('Bavaria C38', 'Bavaria Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.72}'::jsonb),
('Bavaria C42', 'Bavaria Yachts', '{"type":"keelboat","crew":7,"one_design":true,"loa_m":12.99}'::jsonb),
('Bavaria C45', 'Bavaria Yachts', '{"type":"keelboat","crew":8,"one_design":true,"loa_m":14.27}'::jsonb),
('Bavaria Cruiser 34', 'Bavaria Yachts', '{"type":"keelboat","crew":5,"one_design":true,"loa_m":10.36}'::jsonb),
('Bavaria Cruiser 37', 'Bavaria Yachts', '{"type":"keelboat","crew":6,"one_design":true,"loa_m":11.30}'::jsonb)

ON CONFLICT (name) DO UPDATE SET
  class_association = EXCLUDED.class_association,
  metadata = EXCLUDED.metadata;
