-- ============================================================================
-- Fix: Update Head-to-Toe Assessment lesson with region-specific competencyAreas
-- ============================================================================
-- The original seed had all steps with competencyArea = "Assessment" (generic).
-- BodyAssessmentInteractive filters steps by specific competencyArea values
-- like "Neurological Assessment", "Respiratory Assessment", etc.
-- This migration updates the lesson_data with 17 properly categorized steps.
-- ============================================================================

UPDATE betterat_lessons
SET lesson_data = '{
  "lessonId": "nursing-1-1",
  "competencyIds": [1],
  "kolbPhase": "thinking",
  "steps": [
    {"stepNumber": 1, "label": "General Survey", "description": "Assess overall appearance, behavior, and vital signs before hands-on assessment.", "details": ["Level of consciousness and orientation", "Skin color, moisture, and temperature", "Posture, gait, and mobility", "Signs of distress or pain"], "action": "OBSERVE", "criticalAction": false, "competencyArea": "General Assessment"},
    {"stepNumber": 2, "label": "Vital Signs Baseline", "description": "Obtain and document a full set of vital signs.", "details": ["Blood pressure (both arms if first assessment)", "Heart rate, respiratory rate, temperature", "SpO2 on room air", "Pain assessment using validated scale (0-10)"], "action": "PERFORM", "criticalAction": true, "competencyArea": "Vital Signs"},
    {"stepNumber": 3, "label": "Pain Assessment", "description": "Perform a systematic pain assessment using OPQRST mnemonic.", "details": ["Onset — when did it start?", "Provocation/Palliation — what makes it better or worse?", "Quality — sharp, dull, burning, aching?", "Region/Radiation — where does it hurt, does it radiate?", "Severity — 0-10 scale", "Timing — constant or intermittent?"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Pain Assessment"},
    {"stepNumber": 4, "label": "Head & Face", "description": "Inspect and palpate head, eyes, ears, nose, and throat structures.", "details": ["PERRLA — pupils equal, round, reactive to light and accommodation", "Oral mucosa moisture and color", "Facial symmetry assessment", "Lymph node palpation (cervical chain)"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Head Assessment"},
    {"stepNumber": 5, "label": "Neurological Screen", "description": "Assess level of consciousness, orientation, cranial nerves, and motor/sensory function.", "details": ["Glasgow Coma Scale (if indicated)", "Orientation to person, place, time, situation", "Cranial nerve screening (I–XII)", "Pupil size and reactivity"], "action": "PERFORM", "criticalAction": true, "competencyArea": "Neurological Assessment"},
    {"stepNumber": 6, "label": "Neck Assessment", "description": "Assess neck structures including JVD, tracheal alignment, and ROM.", "details": ["Neck ROM and pain with movement", "JVD assessment at 45 degrees", "Tracheal position (midline?)", "Thyroid palpation", "Carotid pulse (one side at a time!)"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Head Assessment"},
    {"stepNumber": 7, "label": "Chest & Lungs", "description": "Auscultate lung sounds bilaterally in all fields.", "details": ["Anterior and posterior auscultation", "Normal: vesicular, bronchial, bronchovesicular", "Adventitious: crackles, wheezes, rhonchi, stridor", "Symmetry of chest expansion"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Respiratory Assessment"},
    {"stepNumber": 8, "label": "Respiratory Pattern", "description": "Assess breathing effort, respiratory rate, and oxygenation.", "details": ["Respiratory rate and depth (12-20 normal)", "Use of accessory muscles", "Cough quality and sputum character", "SpO2 target >94% (or >88% for COPD)"], "action": "OBSERVE", "criticalAction": false, "competencyArea": "Respiratory Assessment"},
    {"stepNumber": 9, "label": "Heart Sounds", "description": "Auscultate heart sounds at 5 anatomical landmarks.", "details": ["Aortic, pulmonic, Erb point, tricuspid, mitral", "S1 and S2 identification", "Check for murmurs, gallops, rubs", "Rate and rhythm assessment"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Cardiac Assessment"},
    {"stepNumber": 10, "label": "Peripheral Vascular", "description": "Assess peripheral circulation including pulses and capillary refill.", "details": ["Peripheral pulse assessment (radial, pedal, posterior tibial)", "Capillary refill time (<3 seconds normal)", "Edema assessment (+1 to +4)", "Skin color and temperature of extremities"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Cardiac Assessment"},
    {"stepNumber": 11, "label": "Abdomen", "description": "Inspect, auscultate, percuss, and palpate all four quadrants.", "details": ["Always auscultate BEFORE palpation", "Bowel sounds: present, absent, hyperactive, hypoactive", "Tenderness, guarding, rigidity", "Liver and spleen assessment"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Abdominal Assessment"},
    {"stepNumber": 12, "label": "GI/GU Review", "description": "Complete abdominal assessment with GI/GU review.", "details": ["Last bowel movement — consistency, color", "Urinary output and characteristics", "Nausea, vomiting, appetite changes", "Abdominal distension or ascites"], "action": "OBSERVE", "criticalAction": false, "competencyArea": "Abdominal Assessment"},
    {"stepNumber": 13, "label": "Upper Extremity Assessment", "description": "Assess upper extremity motor function, sensation, and circulation.", "details": ["Muscle strength grading (0-5) bilateral", "Hand grip strength comparison", "Sensation to light touch", "IV site assessment if applicable", "ROM of shoulders, elbows, wrists"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Upper Extremity"},
    {"stepNumber": 14, "label": "Lower Extremity Assessment", "description": "Assess lower extremity motor function, circulation, and mobility.", "details": ["Muscle strength grading bilateral", "Pedal and posterior tibial pulses", "Edema assessment (+1 to +4)", "Deep tendon reflexes (patellar, Achilles)", "Gait assessment if ambulatory"], "action": "PERFORM", "criticalAction": false, "competencyArea": "Lower Extremity"},
    {"stepNumber": 15, "label": "Skin Survey", "description": "Perform a complete skin assessment from head to toe.", "details": ["Color, turgor, moisture, temperature", "Rashes, lesions, or bruising", "Pressure injury risk areas (sacrum, heels, occiput)", "Braden Scale assessment for at-risk patients"], "action": "OBSERVE", "criticalAction": false, "competencyArea": "Skin Assessment"},
    {"stepNumber": 16, "label": "Wound Assessment", "description": "Assess any wounds, surgical sites, or skin breakdown.", "details": ["Wound size, depth, and stage", "Wound bed appearance (granulation, slough, eschar)", "Surrounding skin condition", "Drainage: type, amount, odor", "Dressing integrity"], "action": "OBSERVE", "criticalAction": false, "competencyArea": "Wound Assessment"},
    {"stepNumber": 17, "label": "Documentation", "description": "Document findings systematically using your facility EHR template.", "details": ["Document normal AND abnormal findings", "Use objective, measurable terms", "Note patient-reported symptoms vs observed signs", "Flag critical findings for immediate provider notification"], "action": "DOCUMENT", "criticalAction": false, "competencyArea": "General Assessment"}
  ]
}'::jsonb,
    updated_at = now()
WHERE id = 'd2000000-0000-0000-0000-000000000001';
